### ISSUE TITLE
Reunião com a Reitoria da UFOB

### ISSUE THREAD

**Issue by RedeDSBR** [Rede-DSBR/CecateNE#102]
## [Reunião: Pesquisadores Educacionais do Transporte Escolar | Cecate Nordeste](https://www.google.com/calendar/event?eid=Nm82YTVxa3RkNjNub2YwaWU1YjNhcjdjaTggY19jNGJiZmE2MzkzYzhlYmYwMWY5MzA1NTkxZTIyYmU3ZWI0MzVmZWIwMWZmYThjMjY2ZjgxODk2M2I4NzhkMTQ0QGc)

📅 **Data:** 17/01/2024
🕒 **Horário:** 14:00 - 15:00  
📝 **Pauta:** Discussão, ideias e propostas sobre a vinculação de Pesquisadores Educacionais do Transporte Escolar à Universidade Federal do Oeste da Bahia.
👥 **Participantes:** [Catia Pereira Aires de Alencar](mailto:catia.alencar@ufob.edu.br), [Professor Duda Bastos](mailto:eduardo.bastos@ufob.edu.br), [Jacques Antonio de Miranda](mailto:jacques.miranda@ufob.edu.br), [Kelli Consuelo Almeida de Lima Queiroz](mailto:kelli.consuelo@ufob.edu.br)

### 📝 Resumo:

Na reunião da Coordenação do Projeto realizada com o Reitor da Universidade Federal do Oeste da Bahia, o professor Jacques Antonio de Miranda, foi realizada uma atualização geral do Projeto Cecate Nordeste e apresentada a necessidade de concessão de bolsas por fundação de apoio para Pesquisadores Colaboradores que atuarão no desenvolvimento da Política Nacional do Transporte Escolar da região nordeste e que, necessariamente, não estejam vinculados à UFOB. Apresentamos marcos congêneres de outras Instituições, refletimos sobre a importância da inclusão de pessoas da comunidade externa nas ações da UFOB nas ações de Pesquisa e de Extensão e avaliamos o impacto da medida nos regramentos da Universidade Federal do Oeste da Bahia. Avaliamos pela necessidade da inclusão do ator colaborador externo na Comunidade Universitária da UFOB na forma do Art. 13 do Regimento Geral da UFOB. Para tanto entendeu-se pela discussão de minuta de resolução, a princípio, na Câmara de Ensino, Pesquisa e Extensão criando a previsão, regulamentando a atividade e realizando as alterações necessárias nos regramentos institucionais. A tramitação da medida ocorrerá em caráter de prioridade e o Reitor, que manifestou apoio à nossa proposta e comprometeu-se com a convocação de reunião em caráter extraordinário considerando o período de recesso dos Conselhos Superiores e a previsão de Lançamento de Edital para seleção de pesquisadores educacionais, além do lançamento do Cecate Nordeste que ocorrerá entre os dias 12 e 14 de março de 2024.

### 🚀 Encaminhamentos:

- [ ] Encaminhar exposição de motivos à Pró-Reitoria de Planejamento e Desenvolvimento Institucional (Proplan/UFOB) apresentando a necessidade de apreciação do tema pelos Conselhos Superiores da UFOB.

### 📎 Documentos Discutidos na Reunião

- [Estatuto da Universidade Federal do Oeste da Bahia](https://ufob.edu.br/a-ufob/instrumentos-normativos/Estatuto_UFOB.pdf)
- [Decreto 7423/2010](https://www.planalto.gov.br/ccivil_03/_ato2007-2010/2010/decreto/d7423.htm) - Regulamenta a Lei no 8.958, de 20 de dezembro de 1994, que dispõe sobre as relações entre as instituições federais de ensino superior e de pesquisa científica e tecnológica e as fundações de apoio.
- [Resolução 11/2017 Consuni/UFOB](https://ufob.edu.br/a-ufob/instrumentos-normativos/resolucoes/2017/consuni/resolucao-011-2017-relacoes-entre-a-ufob-e-as-fundacoes-de-apoio.pdf) - Dispõe sobre as relações entre a UFOB e as Fundações de Apoio
- [Parecer nº 00010/2022/NLC/PFUFOB/PGF/AGU](https://drive.google.com/open?id=1dqm7bdptOQvqGoi0iQksIVPYfFgWlt5f&usp=drive_fs) - Parecer da Procuradoria Federal Junto à Universidade Federal do Oeste da Bahia sobre a interpretação do Art. 6º, §10 do Decreto 7.423/2010 em projetos desenvolvidos em conjunto com outras instituições públicas.
- [UNB: Resolução CEPE nº 047/2022](https://sig.unb.br/sigrh/downloadArquivo?idArquivo=2453077&key=3b342fec94164c24fbd8f22a7b703dd7) - Regulamenta a vinculação de Pesquisadores Colaboradores na Universidade de Brasília.
- [UFBA: Regimento Geral, Art. 130, § 1º](https://www.ufba.br/sites/portal.ufba.br/files/Estatuto_Regimento_UFBA_0.pdf) - Institui o Professor Visitante, a ser contratado com recursos da Universidade Federal da Bahia ou recursos captados mediante convênios, será intelectual, pesquisador ou artista de reconhecimento e renome, admitido após manifestação favorável da Congregação da Unidade Universitária, para atender necessidades especiais do ensino ou para atuar em programa institucional de pesquisa/criação/inovação ou extensão universitária.

### 🤳🏽 Imagens

![Image](https://github.com/Rede-DSBR/CecateNE/assets/102130353/72548ac7-9043-4a22-97a1-0f13200b4c92)
![Image](https://github.com/Rede-DSBR/CecateNE/assets/102130353/6493e41c-9bbd-459c-8e4d-e10468871b4e)

**Comment by dudabastos1973** [comment]
obs: esta postagem ocupa o estilo do Thinking DSBR, veja que o pano de fundo (BG) varia em cada postagem, dando mais dinamismo à identidade visual.

**Comment by RedeDSBR** [comment]
Revisão do texto:

O Cecate Nordeste chamou e a UFOB topou 🤜🏽💥🤛🏽: Vamos criar a Rede Nordeste de Pesquisadores Educacionais do Transporte escolar. A reunião com o Reitor Jacques Miranda foi para discutir e planejar uma ação institucional que irá apoiar a abertura do edital de implantação dos primeiros 10 polos territoriais do Transporte Escolar no Nordeste. Nessa ação vamos trazer para o nosso time gente que entende do problema e que está lá no município se esforçando pela melhoria do transporte escolar para toda a comunidade escolar! 📢 Avia logo esse menino 🏃🏿🏃🏻‍♀️ que o ônibus escolar 🚌 tá chegando e a educação tem pressa!
.
.
.
Você sabe o que é o Cecate Nordeste? Deixa que a gente explica!
O Cecate Nordeste, Centro Colaborador de Apoio ao Transporte Escolar da Região Nordeste, é um projeto da UFOB financiado pelo FNDE, Fundo Nacional de Desenvolvimento da Educação, órgão responsável pela execução da maioria das ações e programas da Educação Básica do nosso País, como a alimentação e o transporte escolar.

Sim. E o que danado o Cecate Nordeste vai fazer?
O Cecate Nordeste vai apoiar a formação de profissionais que atuam no Transporte Escolar e a Democratização de Dados da Política Nacional de Transporte Escolar do FNDE para a Região.

Tu sabia que vamos rodar o Nordeste todinho?
Pois é, a Rede Nordeste de Pesquisadores Educacionais do Transporte Escolar implantará 42 polos territoriais sediados nos municípios sede das Regiões Intermediárias da Região Nordeste para formação e apoio às entidades executoras da política nacional do transporte escolar da região nordeste. 

#CecateNordeste #InovaçãoUFOB #PesquisaEducativa #ufob #rededsbr

**Comment by dudabastos1973** [comment]
Maravilha. Como estamos conversando, fazemos a postagem para depois da apresentação da marca do CECATE ou integramos tudo junto?

**Comment by RedeDSBR** [comment]
A marca é outra pauta. O Cecate vai ter perfil específico na Rede. O lançamento da marca deve ser acompanhado pelo lançamento das ferramentas de comunicação, começando pelo instagram. Ao mesmo tempo, vamos fazer uma ação conjunta com o FNDE, os Cecampe e a UFOB para que as pessoas sigam.

**Comment by RedeDSBR** [comment]
Essa semana precisamos criar o domínio. Vamos avaliar.
