### ISSUE TITLE
[🖼️ Conteúdo] Desenvolvimento de Marca Nacional para os Cecates 🧙‍♂️✒️🖍

### ISSUE THREAD

**Issue by dudabastos1973** [Rede-DSBR/CecateNE#112]
# Criação da marca nacional para o CECATE  📝🖼️

## Descrição
Os Centros Colaboradores de Apoio ao Transporte Escolar (Cecates) são unidades de referência e apoio constituídas por Instituições Federais de Ensino Superior (Ifes), para desenvolver ações e projetos no âmbito do Programa Nacional de Apoio ao Transporte do Escolar (Pnate) e do Programa Caminho da Escola, nas áreas de formação de gestores, gestão do conhecimento, monitoramento e avaliação, apoio ao controle social e assistência técnica, com métodos, técnicas e instrumentos aplicados à gestão da Política Pública do Transporte Escolar. Atualmente, o FNDE conta com o Centro Colaborador da Universidade Federal de Goiás (UFG), liderado pelo curso de Engenharia de Transporte da Faculdade de Ciências e Tecnologia. O Cecate/UFG é coordenado pelo Prof. Dr. Willer Luciano Carvalho, que dedica sua pesquisa à área de transporte escolar há mais de uma década. Recentemente um novo capítulo é inaugurado com a participação da UFOB através do nosso grupo que começa a liderar ações que integram os estados do nordeste, nesse sentido liderado pelo Prof. Poty Lucena com a equipe central das professoras Kelly Consuelo e Cátia Alencar e o Prof. Duda Bastos, todos da UFOB.

## 📚 Atividades

1. [x] Estudo preliminar 01
2. [x] Revisão do estudo 01
3. [x] Apresentação 01
4. [x] Alinhamento e assimilação de expectativas 01
5. [x] Revisão do estudo 02
6. [x] Apresentação 02
7. [x] Alinhamento e assimilação de expectativas 02
8. [x] Revisão do estudo 03  (Opcional)
9. [x]  Apresentação 03 (Opcional)
10. [x] Validação final
11. [x] Publicação de Marca (Prazo 06/02/2024)

## Tipo de Conteúdo
Produto de design da marca com branding book

## Tópicos a Serem Abordados
- orientação visual para a identidade do governo atual
- marca com conceito de abordagem estética para representação nacional

## Objetivo do Conteúdo 🎯
criar um elemento sígnico que seja reconhecido nacionalmente

## Público-Alvo 🎯
Toda estrutura da equipe governamental de atuação e público geral que tenha contato com os Centros

## Data de Publicação Prevista 🗓️
31.01.2024

## Mídia 🖼️
Produtos de divulgação para as redes sociais da Rede DSBR (inicialmente)

## Observações Adicionais 📌
A marca deve se posicionar de modo imponente e representativa

## Revisores ✅
@RedeDSBR 
@dudabastos1973 
@joy-araujo 

## Pessoa Responsável 🙋
@dudabastos1973 

## Data de Início 🚀
10/01/2024

## Data de Conclusão Prevista 🏁
22/01/2024

**Comment by RedeDSBR** [comment]
Considero que o ciclo de aprovação e alinhamento da marca foi concluído. Entendo que a postura da marca em letras minúsculas a mais adequada para representar a marca do Cecate Nordeste. Quanto a Padronagem de cor, agora temos maior liberdade de escolha.

![Image](https://github.com/Rede-DSBR/CecateNE/assets/102130353/014220f7-718e-481d-9717-d0bb416fe06d)
