### ISSUE TITLE
Criação do roteiro conversacional para inscrição ao evento

### ISSUE THREAD

**Issue by jalinegm** [Rede-DSBR/CecateNE#136]
Informações a serem coletadas:
Nome
CPF
Telefone
E-mail
Cargo: representante FNDE, representante prefeitura, diretor(a) de escola, professor(a), motorista, outro
Estado
Cidade

**Comment by RedeDSBR** [comment]
## Sugestão
Onde se lê: Obrigado! Clique em Enviar inscrição para enviar suas respostas
Leia-se: Obrigado! Clique em Enviar inscrição para confirmar sua inscrição no evento

**Comment by jalinegm** [comment]
@RedeDSBR tentei fazer a edição, mas essa mensagem só pode ser personalizada se assinasse uma versão paga acima da nossa. Então, para contornar, mudei o botão para "Confirmar inscrição"
