### ISSUE TITLE
Solicitar Cerimonialista da UFOB

### ISSUE THREAD

**Issue by RedeDSBR** [Rede-DSBR/CecateNE#152]

**Comment by Catia1409** [comment]
Minuta de texto para email solicitando cerimonialista: 
Exma. Sra.
Prof.ª Marina Meirelles Paes
Chefia de Gabinete/Reitoria UFOB

Prezada Professora, 

Com nossos melhores cumprimentos, solicitamos o imprescindível apoio da equipe de Cerimonial da UFOB para realizarmos o encontro que marcará a implantação do Centro Colaborador de Apoio ao Transporte Escolar/Cecate Nordeste, na UFOB, com criação do Polo Territorial de Barreiras, o primeiro dos 42 polos territoriais do transporte escolar no Nordeste. 
Este evento contará com a participação de profissionais e gestores dos municípios da Região Oeste da Bahia, conduzido pelo FNDE – Fundo Nacional de Desenvolvimento da Educação, em agenda no período de 12 a 14 de março de 2024 e especificamente precisaremos do Cerimonial na solenidade a ser realizada no dia 13, no Auditório 1 do PU, no horário de 8 às 18:30h.
O evento do Cecate Nordeste será conduzido sob a coordenação da pesquisadora Cátia Alencar, servidora da UFOB, que nos lê em cópia, que entrará em contato com quem for indicado(a) por V.Sa. e a quem deve ser direcionada decisões para ajustes e eventualidades da organização.

Atenciosamente,

Poty ...

**Comment by RedeDSBR** [comment]
O email de solicitação para a Chefia do Gabinete foi encaminhado e programado para entrega às 07:30 do dia 28/02/2024. Obrigado @Catia1409 pelo apoio e parabéns pela entrega!

**Comment by Catia1409** [comment]
Em resposta ao ofício a responsável pelo cerimonial, Heloisa entrou em contato ontem a noite informando quenão estará em Barreiras na data do evento, mas deixará "certo" com Rosilene, a possibilidade de colocar as toalhas, o estandarte da UFOB, e providenciar água na mesa diretiva. Quanto ao arranjo de flores, sugeriu para comprarmos.

Informa ainda que na ausência dela para realizar a cerimônia, em geral, quando o evento é do Centro, um próprio servidor do Centro pode e costuma fazer essa tarefa. Neste caso é interessante vermos com o diretor do CCET quem pode nos ajudar, certo?? 


Encaminhou um roteiro para adaptar, se assim desejarmos.

**Comment by Catia1409** [comment]
[Cerimonial UFOB - Roteiro da solenidade - Jornada Científica - mesa de abertura (1).docx](https://github.com/Rede-DSBR/CecateNE/files/14460412/Cerimonial.UFOB.-.Roteiro.da.solenidade.-.Jornada.Cientifica.-.mesa.de.abertura.1.docx)

**Comment by Catia1409** [comment]
Vou fazer a adaptação deste roteiro para analisarmos.
Sugiro, se possível, convidarmos Silvano para a tarefa de Cerimonialista

**Comment by Catia1409** [comment]
Segue roteiro prévio para análise e contribuições
[Cerimonial UFOB - Roteiro da solenidade LANÇAMENTO CECATE NE.docx](https://github.com/Rede-DSBR/CecateNE/files/14461611/Cerimonial.UFOB.-.Roteiro.da.solenidade.LANCAMENTO.CECATE.NE.docx)

**Comment by RedeDSBR** [comment]
- Hino Nacional, Hino do Estado da Bahia
- Kelli Consuelo Almeida De Lima Queiroz na mesa
- Revisar a ordem dos pronunciamentos observando a igualdade de gênero
   - Sugestão: Jacques, Lívia, Zito, Kelli, Poty
