### ISSUE TITLE
Contratar Intérprete de Libras

### ISSUE THREAD

**Issue by RedeDSBR** [Rede-DSBR/CecateNE#153]
## Atividades Realizadas

- [x] Elaborar descrição do serviço e solicitação de orçamento [2024-03-01];
- [x] Realização de estimativas e cotações [2024-02-29];
- [x] Encaminhamento de pedido para a Fapex [2024-03-01];
- [ ] Ordem de serviço [2024-03-06]
- [ ] Prestação de Serviço [2024-03-13]
- [ ] Ateste da Despesa [2024-03-11]

## Pasta de Arquivos

🗂 [Serviço de Intérprete de Libras](https://drive.google.com/open?id=1kcQJgi74g1sd7wq_y2K6MwAM_XHcPaqj&usp=drive_fs)

**Comment by Kelliconsuelo** [comment]
Descrição parcial da atividade do interprete de Libras. Cotação 
Atividade finalizada por Poty. 
link de documento - https://docs.google.com/document/d/1B_p2_re7gBx1SaChKcmtCQHS-CTC_BLp/edit?usp=drive_link

**Comment by RedeDSBR** [comment]
O processo já foi enviado com os orçamentos realizados.
