### ISSUE TITLE
Aquisição de camisetas

### ISSUE THREAD

**Issue by RedeDSBR** [Rede-DSBR/CecateNE#162]
## Atividades Realizadas

- [x] Realização de estimativas e orçamentos [2024-02-29];
- [x] Encaminhamento de pedido para a Fapex [2024-03-01]; 
- [x] Desenvolvimento e aprovação de modelo [2024-03-01];
- [x] Ordem de serviço [2024-03-02]
- [ ] Recebimento [2024-03-11]
- [ ] Ateste da Despesa [2024-03-11]

## Pasta de Arquivos

🗂 [Serviço de Confecção de Camisetas](https://drive.google.com/open?id=1lDe7QYqNf_oouB5aJgQyeGUQJQ_COH9E&usp=drive_fs)

**Comment by RedeDSBR** [comment]
Prováveis fornecedores, Strieder, Robe Belle

**Comment by Tamiresbarretoo** [comment]
Empresa: M Strieder Confecções
Modelo tradicional
Material: 100% algodão
Cor Branca | estampa frontal Cecate color 28X26
Valor: 1.974,00 | 47 Unidades
Prazo: 45 dias úteis 
Contato: 77 9 9191-7305

Empresa: Robe Belle
Modelo tradicional Gola Redonda
Material: 100% algodão
Cor Branca | estampa frontal Cecate color 28X26
Valor: 2.025,00 | 45 Unidades
Prazo: 
Contato: 77 9 8834-5784

Empresa: Tutto Bianco Uniformes
Modelo tradicional Gola Redonda
Material: 100% algodão
Cor Branca | estampa frontal Cecate color 28X26
Valor:  2.000,00 | 45 unidades
Prazo: encomendando dia 29/02 entrega dia 11/03
Contato: 77 9 9831-1483

**Comment by RedeDSBR** [comment]
## Atualização

O encaminhamento de pedido foi encaminhado para a Fapex [2024-03-01] por email e foi dada a ordem de serviço [2024-03-02] para o modelo desenvolvido e aprovado[2024-03-01];

### Modelo Aprovado

![image](https://github.com/Rede-DSBR/CecateNE/assets/102130353/7db29efb-9b34-4fe8-886c-d0bb778debbe)
