### ISSUE TITLE
Elaboração do formulário para avaliação do evento [🚌 Evento]

### ISSUE THREAD

**Issue by Kelliconsuelo** [Rede-DSBR/CecateNE#176]
Modelo criado:

Estimado (a) participante,

Assim como sua presença no lançamento Cecate Nordeste foi muito valiosa, sua opinião sobre o evento é essencial para a continuidade do trabalho no âmbito dos programas do Transporte Escolar. Por isso, solicitamos o preenchimento do questionário. 

Gratidão pela colaboração.

Indique sua principal motivação para participar do evento.

Nos itens a seguir assinale a resposta de acordo com a escala.
		
1) Data do evento:		(   )Ótimo	(   )Bom	(   )Regular	(   )Não satisfatório
2) Horário (s):		(   )Ótimo	(   )Bom	(   )Regular	(   )Não satisfatório
3) Duração:		(   )Ótimo	(   )Bom	(   )Regular	(   )Não satisfatório
4) Local:		(   )Ótimo	(   )Bom	(   )Regular	(   )Não satisfatório
5) Recepção:		(   )Ótimo	(   )Bom	(   )Regular	(   )Não satisfatório
6) Inscrição:                (   )Ótimo	(   )Bom	(   )Regular	(   )Não satisfatório
7) Divulgação:	(   )Ótimo	(   )Bom	(   )Regular	(   )Não satisfatório
8) Organização geral (   )Ótimo	(   )Bom	(   )Regular	(   )Não satisfatório

Indique dois aspectos que você mais gostou no lançamento do Cecate Nordeste

Indique dois aspectos que você menos gostou no lançamento do Cecate Nordeste

Faça comentários ou sugestões para nos ajudar a melhorar os encontros com o Cecate.

**Comment by jalinegm** [comment]
Formulário criado: https://pt.surveymonkey.com/r/avaliacaoCecate
