### ISSUE TITLE
[⚠️ Erro] Queda do site cecatenordeste.ufob.edu.br

### ISSUE THREAD

**Issue by potyrlucena** [Rede-DSBR/CecateNE#181]
## 📝 Descreva o erro
Queda do site cecatenordeste.ufob.edu.br

## 🎯 Comportamento Esperado
O site cecatenordeste.ufob.edu.br deve estar em pleno funcionamento.

### 💻 Computador Utilizado
 - Sistema Operacional: Windows
 - Navegador: Chrome

**Comment by RedeDSBR** [comment]
O erro ocorre quando acessa o site com o http
http://www.cecatenordeste.ufob.edu.br/

**Comment by gabrieltavaresmelo** [comment]
Problema solucionado através de uma configuração feita no servidor de aplicações realizada por Luiz.

**Comment by RedeDSBR** [comment]
Site testado, problema resolvido!
