### ISSUE TITLE
[🤝🏽 Reunião] Brainstorm CECATE Ne

### ISSUE THREAD

**Issue by dudabastos1973** [Rede-DSBR/CecateNE#184]
## [Reunião: Brainstorm CECATE Ne para materiais de comunicação e design para Formação do Colaborador](URL do Agendamento)

📅 **Data:** [11/04/2024]
🕒 **Horário:** [17:15-18:15]
📝 **Pauta:** [Inserir]
👥 **Participantes:** 
Pelo Cecate Nordeste: [Professor Duda Bastos](mailto:eduardo.bastos@ufob.edu.br), [Professora Jaline Mombach] (mailto:jaline.mombach@iffarroupilha.edu.br)

### 📝 Resumo:
Encontro para discussão de ideias criativas e temáticas para construção visual e conceitual dos materiais de formação.

**Comment by dudabastos1973** [comment]
Encaminhamento: repertório de referência e composição de narrativas a partir da resolução final do plano de formação dos Pólos em Maceió. Voltamos em breve a continuar a discussão

**Comment by dudabastos1973** [comment]
Slides do Plano de Formação em criação

**Comment by jalinegm** [comment]
Atividades finalizadas para o Polo Maceió.
