### ISSUE TITLE
[🖼️ Planejamento Estratégico para cobertura do Evento de Lançamento do Polo CECATE Ne]

### ISSUE THREAD

**Issue by dudabastos1973** [Rede-DSBR/CecateNE#187]
# 📝🖼️ Planejamento das ações para divulgação em mídias sociais da cobertura do Evento de Lançamento dos Pólos CECATE Ne.

## 📖 Descrição
O evento de lançamento do Polo de Maceió é uma oportunidade crucial para destacar e promover os avanços e potenciais desta região. A cobertura deste evento é fundamental para garantir que sua importância seja devidamente comunicada e celebrada. Este documento apresenta um plano estratégico abrangente para a cobertura do evento, visando maximizar o alcance, engajamento e impacto positivo nas partes interessadas.

## 📌 Tipo de Conteúdo
Registros de imagens foto e vídeo. 

## 📚 Tópicos a Serem Abordados
- [Inserir tópico 1]
- [Inserir tópico 2]
- ...

## 🎯 Objetivo do Conteúdo
1.Destacar os acontecimentos presenciais durante a implantação do Polo de Maceió.
2. Engajar e informar o público sobre os desenrolar do Evento.
3. Ampliar a visibilidade do evento e do Polo, tanto localmente quanto globalmente.
4. Criar conteúdos atrativos e compartilháveis para as redes sociais e outros canais de comunicação.

## 🎯 Estratégias
Criação de ideias e trends que potencializem a cobertura e divulgação do Evento durante as etapas.

**Pré-Evento:**
1.Criar um calendário de contagem regressiva nas redes sociais para gerar antecipação.
2. Postagem convidativa para o grande público.
3. Montar estratégia prévia para produzir materiais promocionais, como vídeos teaser e infográficos, para compartilhamentos online.

**Durante o Evento:**
1. Designar a equipe de cobertura para capturar fotos, vídeos e entrevistas em tempo real.
2. Transmitir partes do evento ao vivo nas redes sociais para alcançar um público mais amplo.
3. Estabelecer com a equipe o pensamento estratégico para criar uma previsão de ações e estar preparado para aproveitar as circunstâncias que porventura surgir.

**Pós-Evento:**
1. Criar um álbum de fotos e vídeos destacando os momentos-chave do evento.
2. Publicar artigos e posts de blog recapitulando os destaques e os principais anúncios feitos.
3. Monitorar e responder ativamente ao feedback e às perguntas do público nas redes sociais e outros canais.

## 🗓️ Data de Publicação Prevista
Durante a realização do Evento

## 🛠️ Recursos Necessários
1. conexão wi-fi
2. celular 
3. softwares Capcut e Canva

## 📌 Observações Adicionais
Precisamos dessas ações descritas em um documento, tal como uma versão prévia das pessoas a serem entrevistadas e o que será perguntado. O projeto de formação que está sendo preparado deve ser consultados para maior entendimento do que se trata o Evento.

## ✅ Revisores
@dudabastos1973 
@RedeDSBR 
@jalinegm 

## 🙋 Pessoa Responsável
@Tamiresbarretoo 
@joy-araujo 

## 🚀 Data de Início
12/04/2024

## 🏁 Data de Conclusão Prevista
19/04

**Comment by Tamiresbarretoo** [comment]
A seguir, apresento o planejamento estratégico para a cobertura do evento de Lançamento do Polo CECATE Ne. Neste documento, detalhamos as estratégias planejadas para a otimização da cobertura, com o objetivo de aumentar a visibilidade do evento e promover o engajamento nas redes sociais.

**Pré Evento**

Com o intuito de aumentar o interesse e gerar curiosidade do público, durante os dias que antecedem o evento, iremos criar peças para publicar no feed do instagram como animações, cards e vídeos utilizando de recursos como os elementos visuais da presente na identidade visual e textos instigantes informando quantos dias faltam para o evento. A ideia é que essas postagens da contagem trabalhem pela informação e atualização de nossas atividades e gerem entusiasmo e aumentem o engajamento no perfil. 

**Sugestão de conteúdos estratégicos:**

1. **Apresentação do evento com o “vem aí”:**  O vídeo seria uma animação dinâmica contendo recortes do evento de lançamento em Barreiras, além de imagens e textos envolventes informando sobre a implementação do polo, enfatizando a importância da participação das comunidades e fazendo um pré convite.   

2. **Faltam X dias:** Criar peças gráficas começando a contagem regressiva contendo elementos visuais presentes na marca, imagens e textos atraentes..

3. **Recurso a autoridade (ferramenta de comunicação):**  Reels de Poty e demais lideranças do Projeto convidando, falando sobre a implementação do polo Maceió e fazendo a contagem (precisaria de uma capa seguindo a proposta dos cards)

4. **Remember:** Imagem do acervo relembrando o sucesso do lançamento Cecate em Barreiras enfatizando que nosso compromisso continua/começa  

5. **Inscrições:** Card  informando que as inscrições estão abertas e o link está disponível na biografia/ ou vídeo curto da equipe de comunicação (Joyce e Tamires)  informando isso e fazendo um mini tutorial ambos de forma intuitiva 

6. **Local confirmado:** o card no feed informaria o local do evento destacando a preocupação do Cecate em oferecer uma experiência ímpar, conforto e acessibilidade.

7. **Postagem convidativa:** estudar proposta do card final que será postado próximo ao evento reafirmando as informações que foram postadas antes (como local confirmado, programação, data, horário) e convidando finalmente o público para o evento com texto mais cerimoniais e formais.

8. **Radar Memes:** pesquisar vídeos de humor que estejam em alta no mês de Maio da região para reproduzir no pré e durante e aumentar a entrega de conteúdos no instagram.

9. **On time:** Criar cards informando o que está acontecendo no evento, principalmente a partir de quem registra (imagens e vídeos) e sobem na nuvem para acessarmos o material bruto para produzirmos o conteúdo. 


10. **Stories**: Criar storytelling da cobertura pelos stories para gerar conexão com o público (Preparativos, viagem, coffee break, dia do evento, participação das pessoas, reuniões da equipe etc)


11. **Ferramenta:** Usar o sticker de localização de Maceió e do local do evento em todas as publicações do instagram no pré evento para começar alcançar esse público desde então.

12. **Menções e colaborações:** postagens em colaboração com o fnde, mec, undime alagoas, uncme alagoas. O intuito é que compartilhem as postagens do evento.

13. **Maceió:** Criar destaque da implementação do Polo nesse estado e em todos os outros seguintes 

14. **Destaques:** Criar uma seção de destaque no perfil do Instagram do CECATE, onde todas as postagens relevantes sejam destacadas para aumentar sua visibilidade. (Repetir o mesmo processo para os demais estados.)

**Estratégia prévia para produzir materiais promocionais:**

_Definir Objetivos e Mensagens-Chave:_ Identificar os principais objetivos dos materiais promocionais, como gerar interesse, destacar os pontos-chave do evento e aumentar a participação. Definir as mensagens-chave que devem ser comunicadas nos vídeos teaser e infográficos.

_Produção de Vídeos Teaser:_ De acordo com os temas propostos, edição do material para criar um vídeo teaser dinâmico, com cortes rápidos, transições suaves e elementos visuais atraentes. Adicionar música de fundo ou simula um diálogo roteirizado. 

**Entregáveis:**

1. Para a gravação de vídeos com diálogos claros e nítidos das pessoas filmadas, é ideal o uso de microfones de lapela. 

- Para **Android**, sugerimos a aquisição do modelo ULANZI Microfone de lapela sem fio J12 para telefone USB C, microfone plug-play 2 em 1. Custo de **185,99 no site da Amazon**

Link: https://www.amazon.com.br/ULANZI-Microfone-carregamento-entrevista-transmiss%C3%A3o/dp/B0B38Y8NYY/ref=asc_df_B0B38Y8NYY/?tag=googleshopp00-20&linkCode=df0&hvadid=379714766595&hvpos=&hvnetw=g&hvrand=15384469926421725956&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=1001517&hvtargid=pla-1720256696078&mcid=1b28c3e5ebc330b590d50be4d9a1f0f5&th=1 

- Para **Iphone**, sugerimos a aquisição do modelo ULANZI Microfone Lavalier sem fio J12 para iPhone iPad, microfone 2 em 1 Plug-Play. Custo de **185,99 no site da Amazon.** 

Link: https://www.amazon.com.br/ULANZI-J12-carregamento-entrevista-transmiss%C3%A3o/dp/B09X114FP9/ref=asc_df_B09X114FP9/?tag=googleshopp00-20&linkCode=df0&hvadid=540341134734&hvpos=&hvnetw=g&hvrand=6385650828534146727&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=1001517&hvtargid=pla-1736191783191&mcid=a00f03aa2feb332a916305493eade2b8&th=1 

- Uma **terceira opção** é o Microfone de Lapela Boya By-V20 USB C para Android 2,4GHz Preto Ideal para Gravações Vídeo Podcasts Entrevistas com Transmissão de Áudio Nítida e Estável. **Custo de 302,40 pelo site da Amazon.**

Link: https://www.amazon.com.br/dp/B0CQK6SPJ2?ref_=pfb_spv01_50b9126cd2b1727a941341604dc8340e&tag=igcmapboc-br-20&ascsubtag=pig-GZBO-P11-V01-O1-ppvdbs-MIMNKL&mcid=c91aeb7739be3ebf9906f1400fc213fd&fbclid=IwAR3Mi2cqO_WhWnLK2GjRrpVsKdPDfN5JhTFcNdhgQH2_F41nwotrtSoJh4w_aem_AU4xSuFCfvTPJvaJ1rC_mjicddez2c4aC2Bx2mm4GwTIXQmgI6tqNsgxTgkduJyVR4kHZH2-tv9Ooa5nqSsGyraa 

2. Para garantir a qualidade das fotografias e vídeos do evento, é importante utilizar celulares com alta resolução de câmera. 

3. Elaborar estratégias específicas para cada dia do evento.
 
@RedeDSBR 
@jalinegm 
@dudabastos1973

**Comment by jalinegm** [comment]
@Tamiresbarretoo e @joy-araujo tem algum detalhamento para o "durante o evento" e o "pós-evento" ?

**Comment by jalinegm** [comment]
Conteúdos criados: 
#235
