### ISSUE TITLE
[⚠️ Erro] Edição do Portal no gerenciador Wordpress sem funcionar

### ISSUE THREAD

**Issue by RedeDSBR** [Rede-DSBR/CecateNE#188]
## 📝 Descreva o erro
Ao tentar editar as páginas do site no gerenciador da página do Cecate Nordeste (https://cecatenordeste.ufob.edu.br/wp-admin/) a janela de edição não carrega.

## 🔄 Para Reproduzir
Passos para reproduzir o comportamento:
1. Abra a página https://cecatenordeste.ufob.edu.br/wp-admin/

![Image](https://github.com/Rede-DSBR/CecateNE/assets/102130353/0e32282f-ccf4-4174-9d94-57ab53b58218)

2. Tente editar alguma página:

![Image](https://github.com/Rede-DSBR/CecateNE/assets/102130353/89ccf9ef-122a-48cc-b766-6f42a209af24)

3. A tela não é processada

![Image](https://github.com/Rede-DSBR/CecateNE/assets/102130353/96ea2f7a-090c-4f07-bb83-f36f81f492f5)

## 🔍 Informações Complementares

 - Navegador: Chrome

**Comment by gabrieltavaresmelo** [comment]
Foi identificado que o problema acontece devido a uma diretiva inserida no servidor NGINX (require-trusted-types-for: 'script') e o Google Chrome não permite a execução dessa página. No entanto, no navegador Firefox o problema não ocorre.

Referências:
https://docs.w3cub.com/http/headers/content-security-policy/require-trusted-types-for.html
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/require-trusted-types-for
