### ISSUE TITLE
Programação preliminar do evento

### ISSUE THREAD

**Issue by potyrlucena** [Rede-DSBR/CecateNE#190]
### 📅 Programação Preliminar

| Data       | Horário       | Atividade                                                                                   | Local       |
|------------|---------------|---------------------------------------------------------------------------------------------|-------------|
| 28/05/2024 | 08:00 - 09:00 | Credenciamento                                                                              | A definir   |
| 28/05/2024 | 09:00 - 10:30 | Abertura oficial, acolhida dos participantes e lançamento do polo Maceió do Cecate Nordeste | A definir   |
| 28/05/2024 | 10:30 - 12:00 | Atividades da formação com gestores das políticas do transporte escolar                     | A definir   |
| 28/05/2024 | 12:00 - 14:00 | Intervalo para almoço                                                                       | A definir   |
| 28/05/2024 | 14:00 - 17:30 | Atividades da formação com os gestores das políticas do transporte escolar e roda de conversa com o FNDE | A definir |
| 28/05/2024 | 17:30 - 18:00 | Avaliação das atividades formativas e encerramento do encontro presencial.                   | A definir   |
| 29/05/2024 | 08:00 - 09:00 | Acolhida dos participantes                                                                  | A definir   |
| 29/05/2024 | 09:00 - 12:00 | Atividades da formação com conselheiros do CACS                                             | A definir   |
| 29/05/2024 | 12:00 - 14:00 | Almoço                                                                                      | A definir   |
| 29/05/2024 | 14:00 - 17:30 | Atividades da formação com conselheiros do CACS e Roda de conversa com o FNDE               | A definir   |
| 29/05/2024 | 17:30 - 18:00 | Avaliação das atividades formativas e encerramento do encontro presencial                   | A definir   |

**Comment by RedeDSBR** [comment]
A programação preliminar foi publicada.

**Comment by RedeDSBR** [comment]
### Programação Atualizada

| Item | Data       | Horário            | Atividade                                                                                        | Público                                                                                                        | Número de Pessoas             | Local                                                                                                      |
|------|------------|--------------------|--------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------|-------------------------------|------------------------------------------------------------------------------------------------------------|
| 1    | 27/05/2024 | A partir das 16:00 | Montagem e organização dos Espaços.                                                              | Responsáveis: Equipe Cecate Nordeste e parceiros                                                               | Aproximadamente 06 pessoas    | Montagem: Auditório, Anfiteatro, Sala de Informática ou outro espaço que possa receber dinâmicas           |
| 2    | 28/05/2024 | 08:00 - 09:00      | Recepção e Credenciamento                                                                        | Fluxo de cerca de 200 pessoas que chegarão ao evento                                                           | 200 pessoas                   | Área em frente ao auditório                                                                               |
| 3    | 28/05/2024 | 09:00 - 10:30      | Abertura oficial, acolhida dos participantes e lançamento do polo Maceió do Cecate Nordeste       | Autoridades, dirigentes, secretários, pessoas responsáveis pelos programas do transporte escolar e representantes dos CACS-Fundeb | Aproximadamente 200 pessoas  | Auditório Principal                                                                                       |
| 4    | 28/05/2024 | 10:30 -12:00       | Atividades da formação Cecate Nordeste e roda de conversa com o FNDE                              | Pessoas responsáveis pelos programas do transporte escolar e representantes dos CACS-Fundeb                   | Cerca de 100 Pessoas, divididas em 02 grupos | Anfiteatro e Sala de Informática ou outro espaço que possa receber uma dinâmica com grupos de trabalho    |
| 5    | 28/05/2024 | 12:30 -13:00       | Desmontagem do Auditório Principal e área em frente ao auditório                                  | Responsáveis: Equipe Cecate Nordeste e parceiros                                                               | Aproximadamente 06 pessoas    | Desmontagem: Auditório Principal e Espaço de recepção e credenciamento, no que couber.                      |
| 6    | 28/05/2024 | 12:00 -14:00       | Intervalo para almoço                                                                            | Não será servido almoço                                                                                        | Cerca de 100 Pessoas          | Procurar locais para indicar aos participantes.                                                           |
| 7    | 28/05/2024 | 14:00 - 17:30      | Atividades da formação Cecate Nordeste e roda de conversa com o FNDE                              | Pessoas responsáveis pelos programas do transporte escolar e representantes dos CACS-Fundeb                   | Cerca de 100 Pessoas, divididas em 02 grupos | Anfiteatro e Sala de Informática ou outro espaço que possa receber uma dinâmica                            |
| 8    | 28/05/2024 | 17:30 - 18:00      | Avaliação das atividades formativas e encerramento do encontro presencial.                        | Pessoas responsáveis pelos programas do transporte escolar e representantes dos CACS-Fundeb                   | Cerca de 100 Pessoas          | Anfiteatro                                                                                                 |
| 9    | 29/05/2024 | 07:30 - 08:30      | Montagem do Auditório e área de recepção e credenciamento                                         | Responsáveis: Equipe Cecate Nordeste e parceiros                                                               | Aproximadamente 06 pessoas    | Montagem: Auditório e área de recepção e credenciamento                                                    |
| 10   | 29/05/2024 | 08:30 - 09:00      | Recepção e credenciamento                                                                        | Pessoas responsáveis pelos programas do transporte escolar e representantes dos CACS-Fundeb                   | Cerca de 100 Pessoas          | Área em frente ao auditório                                                                               |
| 11   | 29/05/2024 | 09:00 - 12:00      | Atividades da formação Cecate Nordeste e roda de conversa com o FNDE                              | Pessoas responsáveis pelos programas do transporte escolar e representantes dos CACS-Fundeb                   | Cerca de 100 Pessoas          | Auditório principal, Anfiteatro, Sala de Informática ou outro espaço que possa receber uma dinâmica com grupos de trabalho |
| 12   | 29/05/2024 | 12:00 -14:00       | Almoço                                                                                           | Não será servido almoço                                                                                        | Cerca de 100 Pessoas          | Procurar locais para indicar aos participantes.                                                           |
| 13   | 29/05/2024 | 14:00 - 17:30      | Atividades da formação Cecate Nordeste e roda de conversa com o FNDE                              | Pessoas responsáveis pelos programas do transporte escolar e representantes dos CACS-Fundeb                   | Cerca de 100 Pessoas          | Auditório principal e/ou Anfiteatro                                                                       |
| 14   | 29/05/2024 | 17:30 - 18:00      | Avaliação das atividades formativas e encerramento do encontro presencial                         | Pessoas responsáveis pelos programas do transporte escolar e representantes dos CACS-Fundeb                   | Cerca de 100 Pessoas          | Auditório principal e/ou Anfiteatro                                                                       |
| 15   | 29/05/2024 | 18:00 – 18:30      | Desmontagem: Auditório e área de recepção e/ou anfiteatro                                          | Responsáveis: Equipe Cecate Nordeste e parceiros                                                               | Aproximadamente 06 pessoas    | Desmontagem: Auditório e área de recepção e/ou anfiteatro                                                  |

**Comment by RedeDSBR** [comment]
## 📅 Programação Final

| Item | Data       | Horário        | Atividade                                                                       | Facilitador                          | Apresentação                                                                           | Local              |
|------|------------|----------------|---------------------------------------------------------------------------------|--------------------------------------|----------------------------------------------------------------------------------------|--------------------|
| 01   | 28/05/2024 | 08:30 – 09:00  | Recepção e credenciamento                                                       | Equipe Cecate Nordeste               |                                                                                        | Hall de entrada    |
| 02   | 28/05/2024 | 09:00 – 09:45  | Solenidade de Abertura                                                          | Mesa Solene                          |                                                                                        | Auditório Principal|
| 03   | 28/05/2024 | 09:45 – 10:30  | Apresentação do Cecate Nordeste e lançamento do Polo Maceió do Cecate Nordeste  | Poty Rodrigues de Lucena             | Centro Colaborador de Apoio ao Transporte Escolar da Região Nordeste • Cecate Nordeste | Auditório Principal|
| 04   | 28/05/2024 | 10:30 – 12:00  | Exposição com diálogos sobre os direitos à educação escolar, os programas do transporte escolar e a gestão dessas políticas no âmbito dos entes federados | Kelli Consuêlo Almeida de Lima Queiroz | 1. Apêndice C/D Linha do Tempo e Cordel                                                | Auditório Principal|
| 05   | 28/05/2024 | 12:00 – 14:00  | Horário de Almoço                                                               |                                      |                                                                                        |                    |
| 06   | 28/05/2024 | 14:00 – 17:00  | Exposição com diálogos sobre as atividades específicas realizadas pelos gestores dos programas do transporte escolar | Kelli Consuêlo Almeida de Lima Queiroz | 1. Apêndice E- Reportagem; 2. Apêndice F- CACs; 3. Apêndice G- Regime de Colaboração; 4. Apêndice H- Das prestações de contas; 5. Apêndice I- Critérios de Repasses do PNATE E CE; 6. Apêndice J- Rede de apoio, formação e acompanhamento MEC; 7. Apêndice K- SisCAC; 8. Apêndice L- Ideges PNATE; 9. Apêndice M- Programa Caminho da Escola, tempo de uso; 10. Apêndice N: Diretrizes e orientações para o apoio técnico e financeiro; 11. Apêndice O: Caso 03; 12. Apêndice P: Caso 04 | Auditório Principal |
| 07   | 28/05/2024 | 14:00 – 17:00  | Exposição com diálogos sobre as atividades específicas dos CACS/Fundeb com os programas do transporte escolar | Cátia Pereira Aires de Alencar        | 1. Apêndice E- Reportagem; 2. Apêndice F- CACs; 3. Apêndice G- Regime de Colaboração; 4. Apêndice H- Das prestações de contas; 5. Apêndice I- Critérios de Repasses do PNATE E CE; 6. Apêndice J- Rede de apoio, formação e acompanhamento MEC; 7. Apêndice K- SisCAC; 8. Apêndice L- Ideges PNATE; 9. Apêndice M- Programa Caminho da Escola, tempo de uso; 10. Apêndice N: Diretrizes e orientações para o apoio técnico e financeiro; 11. Apêndice O: Caso 03; 12. Apêndice P: Caso 04 | Sala 01 |
| 08   | 29/05/2024 | 08:30 – 09:00  | Recepção e credenciamento                                                       | Equipe Cecate Nordeste               |                                                                                        | Hall de entrada    |
| 09   | 29/05/2024 | 09:00 – 09:45  | Os dados e o fortalecimento das decisões na gestão educacional                 | Poty Rodrigues de Lucena             | 1. Apêndice B- dados                                                                   | Auditório Principal|
| 10   | 29/05/2024 | 09:45 – 10:45  | Sistema Eletrônico de Gestão do Transporte Escolar (Sete): Necessidades e possibilidades a partir dos relatos de experiências | Marcos Wilians de Jesus Rocha        | Sistemas e Dados do Transporte Escolar                                                 | Auditório Principal|
| 11   | 29/05/2024 | 10:45 – 11:30  | Sistema Eletrônico de Gestão do Transporte Escolar (Sete): Necessidades e possibilidades a partir dos relatos de experiências | Marcos Wilians de Jesus Rocha        |                                                                                        | Auditório Principal|
| 12   | 29/05/2024 | 11:30 – 12:00  | Avaliação e encerramento                                                       | Equipe Cecate Nordeste               |                                                                                        | Auditório Principal|
