### ISSUE TITLE
Reservar local do evento

### ISSUE THREAD

**Issue by potyrlucena** [Rede-DSBR/CecateNE#195]
Necessitamos organizar a reserva de espaços adequados para a realização de um próximo evento em Maceió, com capacidade para, no máximo, 200 pessoas. Atualmente, a Secretaria de Educação utiliza um auditório que suporta apenas 45 pessoas, o que é insuficiente. Portanto, precisamos dispor de um espaço maior que possa acomodar adequadamente todos os participantes e atividades planejadas e acomodar  evento em configuração de auditório, com disponibilidade de internet, equipamentos de áudio e vídeo para apresentações e conferências, espaço para credenciamento e coffee break e avaliar locais como o Centro de Convenções de Maceió e o Centro de Tecnologia da SECTI.

**Comment by RedeDSBR** [comment]
Solicitamos reserva para os dias 28 e 29 de maio de 2024 de espaços Centro de Inovação do Jaraguá da Secretaria de Estado da Ciência, da Tecnologia e da Inovação (Secti-AL) por meio de ofício. Há apenas uma restrição para o auditório principal, que está reservado para um evento na noite do dia 28 de maio de 2024 e que, não será utilizado na tarde deste dia. Utilizaremos os demais espaços disponíveis.

**Comment by RedeDSBR** [comment]
Centro de Formação Professor Ib Gatto Falcão (Cenfor), Centro Educacional de Pesquisa Aplicada (Cepa), Secretaria de Estado da Educação, SEDUC/AL, CEPA, Av. Fernandes Lima, s/n - Pinheiro, Maceió - AL, 57055-055

***
![image](https://github.com/Rede-DSBR/CecateNE/assets/102130353/ff25f110-f3a1-4c24-a406-b58019466e07)
![image](https://github.com/Rede-DSBR/CecateNE/assets/102130353/6df818b2-a124-489d-9700-3a8ee97155cd)

**Comment by RedeDSBR** [comment]
Aa atividades de Formação Polo Maceió [2701] serão desenvolvidas no Centro de Formação Professor Ib Gatto Falcão (Cenfor), Centro Educacional de Pesquisa Aplicada (Cepa), Secretaria de Estado da Educação, SEDUC/AL, CEPA, espaço sob a responsabilidade de Rita de Cascia, Gerente Especial do Centro de Formação Professor Ib Gatto Falcão - GECENFOR. O local já está reservado. Os vídeos do ocal podem ser acessados [aqui](https://drive.google.com/open?id=1tojNGbYIZQbSlRz3k-5Q_iFSg4OL6CQ6&usp=drive_fs).
