### ISSUE TITLE
[🖼️ Miniatura para questionário de diagnóstico do CECATE]

### ISSUE THREAD

**Issue by jalinegm** [Rede-DSBR/CecateNE#200]
# 📝🖼️ Tarefa de Criação de Conteúdo

## 📖 Descrição
Ao compartilhar o link do formulário da Survey Monkey, é possível personalizar a imagem de miniatura, como no exemplo:
![image](https://github.com/Rede-DSBR/CecateNE/assets/37112456/b05524c0-4d92-4e86-84b4-586cdeb507ee)

## 📌 Tipo de Conteúdo
Imagem, de no máximo 2Mb e de 1200 x 630 pixels.

## 🙋 Pessoa Responsável
@dudabastos1973

**Comment by dudabastos1973** [comment]
![Banner Testeira Sirvey Monkey Evento de Lançamento Polo Alagoas](https://github.com/Rede-DSBR/CecateNE/assets/144291118/f879c434-3360-4024-991c-5efa05ca5945)

**Comment by dudabastos1973** [comment]
![Banner Testeira Sirvey Monkey Evento de Lançamento Polo Alagoas Avaliação](https://github.com/Rede-DSBR/CecateNE/assets/144291118/39fdd3a0-8773-4588-b799-d8bdea2dfee6)
![Banner Testeira Sirvey Monkey Evento de Lançamento Polo Alagoas](https://github.com/Rede-DSBR/CecateNE/assets/144291118/906f8fba-9dc2-4bce-b835-1802c420c19f)

**Comment by jalinegm** [comment]
Formulário atualizado.
