### ISSUE TITLE
[🖼️ Miniatura para questionário de avaliação do evento no Polo Maceió]

### ISSUE THREAD

**Issue by jalinegm** [Rede-DSBR/CecateNE#201]
# 📝🖼️ Tarefa de Criação de Conteúdo

## 📖 Descrição
Ao compartilhar o link do formulário da Survey Monkey, é possível personalizar a imagem de miniatura, como no exemplo:

![image](https://github.com/Rede-DSBR/CecateNE/assets/37112456/b05524c0-4d92-4e86-84b4-586cdeb507ee)

A demanda de uma imagem diferente é para que os participantes não confundam com os demais questionários.

## 📌 Tipo de Conteúdo
Imagem, de no máximo 2Mb e de 1200 x 630 pixels.

## 🙋 Pessoa Responsável
@dudabastos1973

**Comment by dudabastos1973** [comment]
![Banner Testeira Survey Monkey Evento de Lançamento Polo Alagoas Avaliação](https://github.com/Rede-DSBR/CecateNE/assets/144291118/95f88e30-ccc8-4fd2-996d-14c7f7ef6724)

**Comment by dudabastos1973** [comment]
![Uploading Banner Testeira Survey Monkey Evento de Lançamento Polo Alagoas Avaliação.jpg…]()

**Comment by jalinegm** [comment]
Material atualizado.
