### ISSUE TITLE
[🚀 Tem coisa nova] Projeto para formação e Planos Específicos de Cada Polo

### ISSUE THREAD

**Issue by Kelliconsuelo** [Rede-DSBR/CecateNE#204]
# 🌟 PROJETO
Registros dos planos específicos para formação de gestores e CACs, em cada pólo, com base no projeto de formação. 

## 📚 Documento de Referência
- Projeto de formação para gestores e conselheiros no âmbito das políticas do transporte escolar: FNDE/Cecate-Ne/UFOB

1. Link 01: 
2. [Materiais de Referência 02](Link 02)

## 📈 PLANOS ESPECÍFICOS PARA CADA POLO
- [x] #218
- [x] #205 
- [x] Elaboração dos casos como estratégia metodológica para promover as análises e discussões pelos participantes; 
- [x] Organização do painel de dados sobre a educação escolar: Estado e Municípios;
- [x] Definição das dinâmicas de exposição dos casos: animação; entrega de caso impresso; dramatização; 
- [x] Elaboração de recursos de apoio para ilustração de questões abordadas no caso: materiais diversos;
- [x] Definição dos casos e dinâmicas para as atividades em grupo: Grupo 1- Gestores e Grupo 2- Conselheiros; 

1. Link 01: 
2. [Materiais de Referência 02](Link 02)

## 🗂️ Pasta de Arquivos
📁 [Pasta de Arquivos da Tarefa](Link para a pasta)

## 📆 Organização do Trabalho
Respo
### 🚀 Data de Início
22/01/2024

**Comment by jalinegm** [comment]
Material criado para o Polo Maceió
https://drive.google.com/drive/u/1/folders/1kXWA-OzbdiWPWLzodglGDmUDS6eH79Mk
