### ISSUE TITLE
Elaboração do Plano específico -  Polo Maceió - 2701;

### ISSUE THREAD

**Issue by Kelliconsuelo** [Rede-DSBR/CecateNE#205]
#📈 PLANOS ESPECÍFICOS
- [x] #206
- [x] #207
- [x] #208
- [x] Elaboração de recursos de apoio para ilustração de questões abordadas no caso: materiais diversos;
- [x] Definição dos casos e dinâmicas para as atividades em grupo: Grupo 1- Gestores e Grupo 2- Conselheiros; 
- [ ]

**Comment by jalinegm** [comment]
Material detalhado na pasta:
https://drive.google.com/drive/u/1/folders/1kXWA-OzbdiWPWLzodglGDmUDS6eH79Mk
