### ISSUE TITLE
Elaboração dos casos como estratégia metodológica para promover as análises e discussões pelos participantes;

### ISSUE THREAD

**Issue by Kelliconsuelo** [Rede-DSBR/CecateNE#206]

**Comment by jalinegm** [comment]
Casos elaborados por @Kelliconsuelo e @Catia1409. Adicionados na pasta do evento de Maceió por @lucrafi22 
https://drive.google.com/drive/u/1/folders/1W7qotbGa6JlS6LA9Eav80WD-Cg9-ZzOf
