### ISSUE TITLE
Organização do painel de dados sobre a educação escolar: Estado e Municípios;

### ISSUE THREAD

**Issue by Kelliconsuelo** [Rede-DSBR/CecateNE#207]

**Comment by jalinegm** [comment]
Curadoria realizada nos dados do Censo 2023 e nos questionários SAEB (2021).
@marcelromano revisou também.

Os arquivos foram colocados no drive: 
https://drive.google.com/open?id=12sI-1a1Z5c5VjJpHOZn4WeCt3bLdj15Y&usp=drive_fs

Design dos slides feitos pelo @dudabastos1973 :
https://www.canva.com/design/DAGEaJcshpU/NqEAe9meQ83GkG11oHTntw/edit?utm_content=DAGEaJcshpU&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
