### ISSUE TITLE
[🖼️ Comunicação para  a chamada do Encontro de Formação do Polo de Maceió 🌵]

### ISSUE THREAD

**Issue by dudabastos1973** [Rede-DSBR/CecateNE#210]
# 📝🖼️ Posts para Divulgação do Lançamento e instalação do Polo de Maceió do Capítulo regional de Alagoas do CECATE Ne

## 📖 Descrição
Vamos utilizar como base o seguinte texto desenvolvido: 
**Cecate Nordeste e FNDE Lançam Encontro de Formação para Gestores do Transporte Escolar em Maceió**
Maceió, Alagoas — Nos dias 28 e 29 de maio de 2024, o Cecate Nordeste em parceria com o Fundo Nacional de Desenvolvimento da Educação (FNDE) promoverá uma importante atividade de formação destinada aos gestores do transporte escolar. O Encontro de Formação inaugura as atividades do Polo da Região Intermediária de Maceió, com 52 municípios na sua área de abrangência, o primeiro dos dois Polos Territoriais do Transporte Escolar do Cecate Nordeste que serão implantados no estado de Alagoas.

O evento será **realizado no Centro de Formação Professor Ib Gatto Falcão**, localizado no Centro Educacional de Pesquisa Aplicada (CEPA) da Secretaria de Estado da Educação (SEDUC/AL), situado na Av. Fernandes Lima, s/n – Pinheiro, Maceió – AL. As instalações incluem um auditório com capacidade para 160 pessoas, várias salas de aula e espaços de convivência, todos preparados para receber os participantes com todo o conforto necessário para um encontro produtivo. 📍 [Gerar o link no Link Tree para localização do evento, na verdade teremos que ter um bloco no Link Tree com os links de acessos importantes para o evento](https://maps.app.goo.gl/as3mSebig2Fagzbq9)

📅 **Confira aqui a Programação Preliminar**
Municípios Participantes
O encontro contará com a presença de dirigentes e técnicos dos municípios que compõem a região intermediária de Maceió. O objetivo é proporcionar um amplo treinamento que abordará desde questões práticas do dia a dia até as políticas mais amplas de gestão do transporte escolar.

👉🏽 **Consulte aqui se seu município participará da formação!
Inscrições abertas**
[🚍 Inscrição Maceió!](https://pt.surveymonkey.com/r/poloMaceio)
As inscrições já estão abertas e continuarão até o dia 21 de maio de 2024. Cada município poderá inscrever até três representantes, incluindo dirigentes e responsáveis pelo transporte escolar, além de representantes dos Conselhos de Acompanhamento e Controle Social do Fundeb (CACS Fundeb). Os interessados devem preencher o formulário disponível no botão acima ou no [link de inscrição](https://pt.surveymonkey.com/r/poloMaceio).

**Apoio Institucional**
Este evento conta com o apoio da União Nacional dos Dirigentes Municipais de Educação (Undime), da União Nacional dos Conselhos Municipais de Educação (Uncme) de Alagoas e da Secretaria de Educação do Estado de Alagoas. A cooperação dessas entidades é fundamental para o sucesso do programa e para a garantia de uma formação de qualidade aos participantes.

**Importância do Evento**
“A formação visa fortalecer a importância do transporte escolar como uma política do estado e a sua capacidade de gerenciamento nos estados e municípios da Região Nordeste. É uma oportunidade única para os gestores atualizarem seus conhecimentos e compartilharem experiências”, afirma o professor Poty Lucena, coordenador do Cecate Nordeste. “Com o apoio e participação do FNDE e de parceiros locais, estamos comprometidos com a formação das políticas do transporte escolar para uma educação de qualidade para todos os estudantes da região.”

Para mais informações sobre o encontro de formação, dúvidas sobre a participação ou processo de inscrição, os interessados podem acessar o site oficial do [Cecate Nordeste](http://www.cecatenordeste.ufob.edu.br/), www.cecatenordeste.ufob.edu.br, ou entrar em contato diretamente pelo Zap do Cecate, telefone (77) 9 9988-9876.

## 📌 Tipo de Conteúdo
Posts para redes sociais Portal de links [Link Tree do CECATE Ne] para acessos ao conteúdo de links do evento. Reproduzir também no linktree da Rede DSBR

## 📚 Tópicos a Serem Abordados
- Comunicar o lançamento
- Divulgar as inscrições
- Fornecer os links
- Disponibilizar o material no link: H:\Drives compartilhados\:arte: Design DSBR\1. CECATE Ne\6. Materiais para Eventos\6.2 Evento de Lançamento Polo Maceió - Alagoas 2024
**Obs: utilizar o formato caixa Alta e baixa nos nomes dos arquivos**

## 🎯 Objetivo do Conteúdo
De acordo com o seguinte esboço:
Confira! 🚌✨ **Encontro de Formação para Gestores do Transporte Escolar em Maceió!** 🎓

📅 **Quando? 28 e 29 de maio de 2024**
📍 **Onde?** Centro de Formação Professor Ib Gatto Falcão, CEPA - Av. Fernandes Lima, Maceió - AL.

Participe do Cecate Nordeste organizado em parceria com o FNDE, **projetado para gestores e técnicos de transporte escolar de 52 municípios**. Amplie seus conhecimentos e troque experiências sobre gestão eficaz do transporte escolar.

👥 **Quem pode participar?** Dirigentes, técnicos do transporte escolar e representantes do CACS Fundeb.
👉🏽 I**nscrições abertas até 21 de maio de 2024!** [Inscrição Maceió!](https://chat.openai.com/c/link)

🔍 **Por que participar?**

Formação especializada em gestão do transporte escolar.
Troca de experiências com outros gestores da região.
Apoio de importantes instituições educacionais.
Não perca essa oportunidade de aprimoramento profissional e de contribuir para a melhoria da qualidade do transporte escolar em sua região!

Para mais informações e inscrições, acesse [www.cecatenordeste.ufob.edu.br](http://www.cecatenordeste.ufob.edu.br/) ou entre em contato pelo Zap do Cecate: (77) 9 9988-9876.

## 🎯 Público-Alvo
Dirigentes, técnicos do transporte escolar e representantes do CACS Fundeb.

## 🗓️ Data de Publicação Prevista
06.05.2024

## 🖼️ Mídia
Formatos 1080x1080; 1080x1920
Banco de imagens: https://drive.google.com/drive/folders/1YAzjPHqLiJgjnEwAUmOCoSFN1FC1gjBu

## ✅ Revisores
- @dudabastos1973 
- @RedeDSBR 
- @Kelliconsuelo 
- @Catia1409 
- @jalinegm 

## 🙋 Pessoa Responsável
@Tamiresbarretoo 
@joy-araujo 
@dudabastos1973 

## 🚀 Data de Início
03.05.2024

## 🏁 Data de Conclusão Prevista
06.05.2024

**Comment by RedeDSBR** [comment]
# Cobertura Maceió [2701]

🚨 **O evento de Maceió e as inscrições serão divulgadas na Segunda-feira (06/05/2024)**

- [ ] Combinar as postagens conjuntas com as equipes dos parceiros da Undime Alagoas, Uncme Alagoas e Secretaria de Educação do Estado.
- [ ] Inserir nas nossas publicações a parceria com a Undime Alagoas, Uncme Alagoas e Secretaria de Educação do Estado.
- [ ] Marcar como colaborador nas postagens.
- [ ] Preparar kit de marca Maceió para compartilhar com a Undime, Uncme e Secretaria de Educação. 

## 📸Fotos disponíveis no Facebook da Undime

https://www.facebook.com/profile.php?id=100066267680673&sk=photos

Existe bastante fotos dos nossos parceiros na internet. Façam uma busca e confirmem a autorização e oportunidade de postar a foto.

### Depoimentos fornecidos

"O transporte escolar é uma das ferramentas mais importantes para assegurar que a comunidade escolar tenha acesso às unidades educacionais e, principalmente, garantir que todos tenham as mesmas oportunidades de educação e conhecimento. É o elo entre a realidade individual de cada discente e a expectativa de construção de um futuro melhor". George Paes, Superintendente de Frota e Transporte Escolar de Alagoas.

“O transporte escolar exerce papel fundamental no acesso à educação de crianças e jovens. Capacitar os municípios é fundamental para fortalecer a oferta de um transporte escolar eficiente e seguro, promovendo não apenas a igualdade de oportunidades educacionais, mas também o bem-estar e a segurança dos nossos alunos.” Djalma Barros, Presidente da União dos Dirigentes Municipais de Educação, Undime Alagoas.

(Falta Depoimento)
Marly do Socorro Peixoto Vidinha, União Nacional dos Conselhos Municipais de Educação-UNCME, Presidente do Conselho Estadual de Educação de Alagoas **(Conferir os cargos)**

### Contato

Sempre entrar em contato com as representações dos Fóruns para alinhar as postagens e divulgações, **isso é prioridade**. Os contatos já estão no nosso grupo do Cecate Maceió.

**Comment by dudabastos1973** [comment]
![Inscrições abertas Polo Maceió](https://github.com/Rede-DSBR/CecateNE/assets/144291118/dd907a93-d733-46e9-97b6-8f808323b9f0)

**Comment by dudabastos1973** [comment]
Para apreciação geral
![Inscrições abertas Polo Maceió](https://github.com/Rede-DSBR/CecateNE/assets/144291118/fe497646-880f-4f42-96dd-088e8ba1581f)

**Comment by dudabastos1973** [comment]
![Inscrições abertas Polo Maceió](https://github.com/Rede-DSBR/CecateNE/assets/144291118/b1dce7ac-ea38-4b99-b318-1834bb41c277)

**Comment by Catia1409** [comment]
Faltou a data da Formação e o link para inscrições
*Cátia Alencar*
Técnica em Assuntos Educacionais/PROGRAD


Em seg., 6 de mai. de 2024 às 10:05, Duda Bastos ***@***.***>
escreveu:

**Comment by dudabastos1973** [comment]
![image](https://github.com/Rede-DSBR/CecateNE/assets/144291118/4ba706ad-fc28-4e81-a08a-59e4839513a2)
