### ISSUE TITLE
[🚀 Tem coisa nova] Indexar o site do CecateNe no Google 

### ISSUE THREAD

**Issue by jalinegm** [Rede-DSBR/CecateNE#219]
## 🌟 Descrição
Ajustar palavras-chave e meta-descrição no site do CecateNe para facilitar a indexação pela busca Google.

## 👤 Pesquisador líder da tarefa
@gabrieltavaresmelo 

## 🎯 Problema Crítico
Ao buscar "Cecate Nordeste" no Google hoje, os resultados mostram a página do projeto no site da DSBR e até mesmo um evento que não foi realizado na plataforma Even3. O objetivo é pesquisar estratégias para facilitar a indexação pelo motor de busca do Google. Assim, o site oficial do Cecate Nordeste poderá figurar entre os primeiros resultados da busca. 

![image](https://github.com/Rede-DSBR/CecateNE/assets/37112456/c73fb2a8-d7b7-4972-8d11-09951f5f8d51)

## 📈 Meta do Plano de Trabalho
[2.4. Produção de artefatos de comunicação e produção de mídias digitais para Rede Nordeste de Pesquisadores Educacionais do Transporte Escolar](https://github.com/Rede-DSBR/CecateNE/milestone/20)

## 💡 Sugestões para Resolver o Problema
- [ ] ✅ Revisar as palavras-chave que estão sendo usadas atualmente.
- [ ] 🔍 Revisar a meta-descrição dos posts e páginas vinculadas ao site.
- [x] 🔍 Analisar possibilidade de cadastrar no site do Google Search Console.
- [x]  Configurar indexação e solicitar reindexação da página. 
- [x] Configurar e gerar Sitemap
- [ ] 💡 Revisar as descrições de imagens que estão publicadas no site.
- [ ] 📚 Pesquisar demais estratégias de SEO que podem colaborar com a demanda.

## 🙋 Revisores
@dudabastos1973 
@RedeDSBR 

### 🚀 Data de Início
16/05/2024

**Comment by damascenaluiz** [comment]
Feita verificação Google Search e ajuste no Site para indexação. Aguardar acessos e o tempo para analisar ranqueamento

**Comment by damascenaluiz** [comment]
Sitemap também foi gerado para o Google.

**Comment by damascenaluiz** [comment]
Agora figura entre os primeiros utilizando da palavras do descritas abertura da issue.

**Comment by jalinegm** [comment]
Excelente, muito obrigada @damascenaluiz!

**Comment by jalinegm** [comment]
O site agora figura como primeiro resultado na busca Google.
