### ISSUE TITLE
[🖼️ Divulgação prorrogação das inscrições e mudança de local do Evento de Lançamento Polo Maceió]

### ISSUE THREAD

**Issue by dudabastos1973** [Rede-DSBR/CecateNE#221]
# 📝🖼️ Cards ou Motions Design envolvendo a prorrogação das inscrições e alteração de Local do Evento de Lançamento do Pólo Maceió

## 📖 Descrição
A pedido do coordenador do Projeto foi solicitado em caráter de urgência a produção de material para essa divulgação.
Serão 2 produtos. Um para divulgação hoje e outro amanhã, conforme os Tópicos.
## 📌 Tipo de Conteúdo
Posts para as redes sociais e compartilhamento no Whatsapp

## 📚 Tópicos a Serem Abordados
Bom dia. Vamos emitir duas comunicação:
1.Vamos prorrogar as inscrições até sexta-feira, 24/05/2024 (Soltar hoje)
2. O local do evento será alterado (Soltar amanhã pela manhã). Será no Auditório Oscar Sátyro do Instituto Federal de Alagoas - Campus Maceió, R. Mizael Domingues, 530, Centro, Maceió, AL.

## 🎯 Público-Alvo
público geral do Evento

## 🗓️ Data de Publicação Prevista
1. 22.05.24
2. 23.05.24

## ✅ Revisores
@dudabastos1973 
@RedeDSBR 
@jalinegm 

## 🙋 Pessoa Responsável
@Tamiresbarretoo 
@joy-araujo 

## 🚀 Data de Início
Hoje. Rammmmm Tchuuuuuuuuuuuu

## 🏁 Data de Conclusão Prevista
Amanhã. 23.05.24

**Comment by Tamiresbarretoo** [comment]
![ IMG_6308](https://github.com/Rede-DSBR/CecateNE/assets/157534013/b6b4944b-37a6-4a80-8a2b-51f43ec3b4ae)

Notícia boa! Para dar ainda mais oportunidade a todos o prazo das inscrições foi prorrogado! 📢🗣️

Agora você tem até 24 de maio de 2024 para garantir sua vaga no evento de inauguração do Polo CECATE Ne em Maceió.📆

Você que é dirigente, conselheiro, técnico do transporte escolar ou representante do CACS-Fundeb faça sua inscrição, não deixe para a última hora! Inscreva-se já! 📝✨

O link para inscrição está na bio, simbora!! 🤩

#CecateNordeste #Lançamento #Maceió #FNDE #UNCME #UNDIME

**Comment by jalinegm** [comment]
Atividade finalizada.
