### ISSUE TITLE
Solicitar Cerimonialista

### ISSUE THREAD

**Issue by potyrlucena** [Rede-DSBR/CecateNE#231]

**Comment by RedeDSBR** [comment]
O cerimonial para a nossa atividade foi conduzida pelo colega Sérgio Barros Correia, Coordenação de Comunicação e Eventos do Campus Maceió do Instituto Federal de Alagoas, IFAL.
Email: comunicacao.maceio@ifal.edu.br     
Fone: (82) 21226-7002
Lattes: http://lattes.cnpq.br/8000435643288878
