### ISSUE TITLE
Elaborar Roteiro do Cerimonial

### ISSUE THREAD

**Issue by potyrlucena** [Rede-DSBR/CecateNE#233]

**Comment by RedeDSBR** [comment]
O [Roteiro do Cerimonial](https://drive.google.com/open?id=13MvBqnKFN49jftSpks18LI_2URorIVTK&usp=drive_fs) foi elaborado e encaminhado para revisão de todas as autoridades. Após  a revisão, o documento foi impresso e entregue ao mestre de cerimônias.
