### ISSUE TITLE
[🖼️Desenvolvimento de conteúdos para o Evento de Formação do Polo CECACE NE em Maceió - AL]

### ISSUE THREAD

**Issue by Tamiresbarretoo** [Rede-DSBR/CecateNE#235]
# 📝🖼️ Peças gráficas para o evento Pré - Evento de Lançamento do Polo Maceió

## 📖 Descrição
Com o intuito de aumentar o interesse e gerar curiosidade do público, nos dias que antecedem o evento, serão criadas peças para publicar no feed e stories do Instagram. Essas peças incluirão cards e vídeos, utilizando elementos visuais presentes na  identidade visual do CECATE Ne, além de textos instigantes que informaram quantos dias faltam para o evento. 

## 📌 Tipo de Conteúdo
Peças gráficas e legendas 

## 📚 Tópicos a Serem Abordados
- Cronograma de postagem  

## 🎯 Objetivo do Conteúdo
A ideia é que essas postagens de contagem trabalhem para manter todos informados e atualizados sobre as atividades, gerando entusiasmo e aumentando o engajamento no perfil.

## 🎯 Público-Alvo
Público geral do Evento

## 🗓️ Data de Publicação Prevista
Pré - evento 

## ✅ Revisores
@dudabastos1973 
@jalinegm 
@RedeDSBR 

## 🙋 Pessoa Responsável
@Tamiresbarretoo 
@joy-araujo 

## 🚀 Data de Início
01/05

## 🏁 Data de Conclusão Prevista
25/05

**Comment by Tamiresbarretoo** [comment]
07/05 Terça-feira - Lançamento Cecate Polo Maceió - AL:  Card de inscrições abertas com depoimentos;
08/05 Quarta-feira - Pé na estrada: Card encontro do Coordenador Poty com representantes da Undime e Uncme; 
16/05 Quinta feira - Card com  a notícia do evento de formação em Maceió - AL no GOV; 
18/05 Sábado - Card faltam 10 dias;
19/05 Domingo - Vídeo do Poty convidando o público;
21/05 Terça-feira - Stories divulgando as inscrições se encerram hoje; 
22/05 Quarta-feira - Prorrogação das inscrições até o dia 24/05;
23/05 Quinta-feira - Faltam 5 dias;
23/05 Quinta-feira - Local do evento alterado; 
25/05 Sábado - Lançamento Cecate Polo Maceió - AL: Card com local, data e horário;

**Comment by joy-araujo** [comment]
08/05 Quarta-feira - Pé na estrada: Card encontro do Coordenador Poty com representantes da Undime e Uncme;

![Prancheta 1](https://github.com/Rede-DSBR/CecateNE/assets/150853958/804b2a12-223c-4033-a108-11a0c8d27011)

**Comment by joy-araujo** [comment]
**- 18/05 Sábado -** Card faltam 10 dias;

![Prancheta 1](https://github.com/Rede-DSBR/CecateNE/assets/150853958/b58aa23e-c853-4cba-acc8-3ded8afaa4b1)

**Comment by joy-araujo** [comment]
**- 23/05 Quinta-feira** - Faltam 5 dias;

![Prancheta 2](https://github.com/Rede-DSBR/CecateNE/assets/150853958/df92b392-e95f-45e9-905d-4cdf221c2d8c)

**Comment by joy-araujo** [comment]
**- 25/05 Sábado** - Lançamento Cecate Polo Maceió - AL: Cartão com local, dados e horário;

![Prancheta 3](https://github.com/Rede-DSBR/CecateNE/assets/150853958/29a21c1b-0d00-4fdc-971f-b963f1b37e98)

**Comment by joy-araujo** [comment]
- **22/05 Quarta-feira -** Prorrogação das inscrições até o dia 24/05;

![Prorrogação](https://github.com/Rede-DSBR/CecateNE/assets/150853958/2f8752aa-59ca-43ee-b4b6-058ee5107027)

**Comment by joy-araujo** [comment]
**- 23/05 Quinta-feira** - Local do evento alterado;

![Local](https://github.com/Rede-DSBR/CecateNE/assets/150853958/a75e5d9d-105d-4567-899c-b346578517b1)

**Comment by jalinegm** [comment]
@joy-araujo coloque os editáveis na pasta do evento, por favor:
https://drive.google.com/open?id=1ejozBUPShcP2xdu6Yinhi2Hcqp8sgPAQ&usp=drive_fs
