### ISSUE TITLE
[🖼️ Conteúdo] Kit de Marca para implementação do Polo CECATE Ne em Campina Grande - PB

### ISSUE THREAD

**Issue by Tamiresbarretoo** [Rede-DSBR/CecateNE#238]
# 📝🖼️ Adaptar e produzir o Kit de Marca de implantação do Polo CECATE Ne em Campina Grande - PB. 

## 📖 Descrição
O evento de formação do Cecate Nordeste ocorrerá em Campina Grande, Paraíba, nos dias 09 e 10 de julho de 2024. Destinado a Responsáveis ​​e Conselheiros do CACS dos Municípios da Região Intermediária, o encontro promoverá formação intensiva, discussão estratégica e troca de práticas com o FNDE para melhorar a gestão e promoção de políticas de transporte escolar.

## 📌 Tipo de Conteúdo
Acervo arquivo do conjunto de aplicações de marca

## 🎯 Público-Alvo
Usuários e Designes do Projeto

## 🗓️ Data de Publicação Prevista
06.06.2024

## 📌 Observações Adicionais
O kit marca será atualizado com as diretrizes específicas para o polo de Campina Grande.

## ✅ Revisores
@RedeDSBR 
@dudabastos1973 
@jalinegm 

## 🙋 Pessoa Responsável
@joy-araujo 
@Tamiresbarretoo 

## 🚀 Data de Início
06/04/2024

## 🏁 Data de Conclusão Prevista
06/06/2024

**Comment by joy-araujo** [comment]
**Kit de Marca de implantação do Polo CECATE Ne em Campina Grande - PB**


- No formato Horizontal: 

![Marca CECATE Ne Alagoas horizontal 2](https://github.com/Rede-DSBR/CecateNE/assets/150853958/4e6d7e83-ece2-4dbe-b856-3849846db978)
![Marca CECATE Ne Alagoas Polo Maceió horizontal Oficial](https://github.com/Rede-DSBR/CecateNE/assets/150853958/452b4989-c655-49d1-bfe6-501a140e521e)
![Marca CECATE Ne Alagoas Polo Maceió horizontal 2 Oficial](https://github.com/Rede-DSBR/CecateNE/assets/150853958/4dc7c5fd-968d-4907-878a-cca42fc68798)

- No Formato Vertical: 

![Marca CECATE Ne Alagoas Polo Maceió vertical](https://github.com/Rede-DSBR/CecateNE/assets/150853958/198a794a-f43e-4a2d-9e1f-01a4acb48092)
![Marca CECATE Ne Alagoas vertical](https://github.com/Rede-DSBR/CecateNE/assets/150853958/7e7f0153-e593-4f77-8d07-b14e8d5e7a96)
