### ISSUE TITLE
Desenvolvimento do plano de comunicação com pré-produção de conteúdos

### ISSUE THREAD

**Issue by jalinegm** [Rede-DSBR/CecateNE#241]
@Tamiresbarretoo e @joy-araujo:
Baseado no que foi planejado para o Polo Maceió (#187), por favor, planejem a estratégia de comunicação para o lançamento do Polo Campina Grande e postem aqui para validação. 

Após validação, já vamos iniciar um calendário de pré-produção para que tu esteja pronto até o dia do evento ;)

**Comment by Tamiresbarretoo** [comment]
**Planejamento Polo Cecate Nordeste em Campina Grande 
09 E 10 DE JULHO**

- Pré Evento: Conteúdos 

_SEGUNDA 17/06 : Local confirmado_
O card no feed informaria o local do evento destacando a preocupação do Cecate em oferecer uma experiência ímpar, conforto e acessibilidade.


_SEXTA 21/06: Carrossel Informativo sobre os Polos_
Criar conteúdo sobre a organização de polos do Cecate Nordeste

_TERÇA 25/06: Reels convidativo after effect (Pode ser um pequeno cordel)_
Sugestão de roteiro: 
1 TAKE/texto:  Próximo destino: (nomenclatura) Rainha da borborema
transição
2 TAKE/texto:  Evento de Lançamento do Polo Cecate Nordeste em  Campina Grande - PB.
transição
3 TAKE: texto - Cortes dos eventos anteriores
transição
4 TAKE: Marcas movimentando
transição
5 TAKE/texto: Cecate Nordeste: Construindo Caminhos para o Futuro
transição
6 TAKE/texto: 09 e 10 de julho

_SÁBADO 29/06: Faltam 10 dias_ 
Criar peças gráficas começando a contagem regressiva contendo elementos visuais presentes na marca, imagens e textos atraentes. Usar sticker de contagem do instagram 

_SEGUNDA 01/06: Caixinha de Perguntas_
Abrir uma caixinha de perguntas 24h nos stories para sanar dúvidas sobre o evento. 

_QUINTA 04/07: Faltam 5 dias_ 
Criar peças gráficas começando a contagem regressiva (colocar elementos visuais presentes na marca, imagens e textos atraentes.) Usar sticker de contagem do instagram 

_SÁBADO 06/07: Postagem convidativa:_
 Card final reafirmando as informações que foram postadas (local, programação, data, horário) e convidando o público para o evento.
 
- Durante: Orientações fotográficas 

Objetivo das Fotografias:
Capturar momentos chave do evento, destacando a presença de autoridades, apresentações, interação dos participantes, infraestrutura do local e detalhes que reforcem a importância e o impacto do Polo Cecate Nordeste.

_Registrar em foto e vídeo:_
Recepção e a chegada dos convidados, incluindo o credenciamento; 
Cerimônia de abertura, incluindo discursos e apresentações;
Interação entre os participantes durante os intervalos;
Ambiente geral, auditório cheio;
Coffee Break (geral e detalhes);
Mesa de apresentação com os convidados;
Imagens diversas dos participantes no display do Cecate Nordeste;
Grupos de participantes em momentos de descontração e networking;
Banners, sinalizações e detalhes que mostram a identidade visual do Cecate Nordeste e a personalização para Campina Grande.

_Depoimentos:_ 
Entrevistas rápidas com participantes, palestrantes e organizadores, perguntando sobre suas expectativas, experiências e impressões do evento. (Lembrar de pedir o participante para fala o nome e o município no início do vídeo)
Depoimentos espontâneos, pedindo às pessoas que compartilhem suas opiniões e sentimentos sobre o evento.

_Entregáveis:_
Compartilhar todo material captado em  um drive ou app google fotos.
Disponibilizar os arquivos em tempo real
Deixar o layout produzido. 

_Postagens:_
Storytelling, postagens do eventos em real time nos stories;
Feed: postagens de fotos, compartilhamento aberto para o público; 
Adicionar as menções e repost no destaques “Vocês” 

- Pós Evento
Time - Lapse do auditório se enchendo (gravar desde ele vazio)
Reels: entrevista com a Lívia e com o Poty sobre o evento (gravar durante o evento)
Reels: Melhores momentos/ resumão
São João áudio em alta: Brincando de Amar - Versão Xand Avião - Reels transição
