### ISSUE TITLE
[🖼️ Conteúdo] Adaptação de materiais para divulgação de inscrição

### ISSUE THREAD

**Issue by jalinegm** [Rede-DSBR/CecateNE#244]
# 📝🖼️ Adaptar e produzir peças para a inscrição - Polo Campina Grande.

## 📖 Descrição
Adaptar as peças já produzidas pelo Duda para utilização na divulgação das inscrições no site do CecateNe e também na miniatura do link do formulário de inscrição.

Adicionar a produção na pasta compartilhada:
https://drive.google.com/open?id=1CgTsJRIVzwFbnMxutwGUCSF8zXRzgnKA&usp=drive_fs

## 📌 Tipo de Conteúdo
Post

## 🖼️ Mídia
Modelos criados pelo Duda:

![form_inscricao](https://github.com/Rede-DSBR/CecateNE/assets/37112456/690f0d69-d4ca-42ca-8cd6-bc9d79ff791f)

![form_avaliacao](https://github.com/Rede-DSBR/CecateNE/assets/37112456/b91e2eea-121d-449c-99ed-a275ac525cb1)

![173696ba-7650-4182-a15d-b1519e0276f4](https://github.com/Rede-DSBR/CecateNE/assets/37112456/6cfe9101-f974-48f1-a259-cfa139dd35c5)

![image](https://github.com/Rede-DSBR/CecateNE/assets/37112456/ff1c1ffe-9e32-4f2b-919c-99fa0f295c77)

## 🙋 Pessoa Responsável
@joy-araujo 

## 🚀 Data de Início
10/06/2024

**Comment by jalinegm** [comment]
![Lançamento CECATE ne](https://github.com/Rede-DSBR/CecateNE/assets/37112456/39eab70b-f7d1-4a62-9d7d-5eaf7c05214e)

**Comment by joy-araujo** [comment]
![Uploading Lançamento CECATE ne.png…]()

**Comment by joy-araujo** [comment]
![Lançamento CECATE ne](https://github.com/Rede-DSBR/CecateNE/assets/150853958/b5318224-07d2-4ce7-a819-be8739cfe6d3)

**Comment by jalinegm** [comment]
@joy-araujo por favor, podes fazer um genérico para os formulários de inscrição? Penso que sem a marca do estado, pois esses formulários não são tão divulgado na url da survey monkey, mas sim na url do site do CecateNe.
São dois: o de inscrição e o de avaliação.

**Comment by joy-araujo** [comment]
Seria neste formato @jalinegm ? 

![Formulário de Avaliação](https://github.com/Rede-DSBR/CecateNE/assets/150853958/02cd30ca-0d87-4af9-94f0-696d26b834b6)
![Formulário de Inscrições](https://github.com/Rede-DSBR/CecateNE/assets/150853958/deab8981-1cad-41d4-8b53-1b6b9420a658)

**Comment by joy-araujo** [comment]
Seria nesse formato @jalinegm ?
![Formulário de Avaliação](https://github.com/Rede-DSBR/CecateNE/assets/150853958/f51dbd66-d6e3-4fc6-a87b-ea723fde61b0)
![Formulário de Inscrições](https://github.com/Rede-DSBR/CecateNE/assets/150853958/469883c4-daf6-471d-b55e-004c3d1292ca)

**Comment by jalinegm** [comment]
@joy-araujo não, na verdade na mesma ideia dos outros, mas com a marca geral do Cecate, sem distinção de Polo. 
Ex:

Pode ser essa, mas sem a linha "Polo Campina Grande" e a marca sem o Paraíba, só Cecate mesmo. 

![image](https://github.com/Rede-DSBR/CecateNE/assets/37112456/4fedfdf8-9eb0-4e90-b8b3-f25b357489e7)

**Comment by joy-araujo** [comment]
Fiz a correção @jalinegm. 
![Formulário de Inscrições](https://github.com/Rede-DSBR/CecateNE/assets/150853958/8f92c098-796c-4a2a-9899-0be0a128109f)
![Formulário de Avaliação](https://github.com/Rede-DSBR/CecateNE/assets/150853958/ba2bb014-4ca9-4b5f-86f1-79fb4f07dd3a)

**Comment by jalinegm** [comment]
@joy-araujo obrigada! <3
