### ISSUE TITLE
[🖼️ Conteúdo]  Kit de Marca para implementação do Polo CECATE Ne em Recife -PE e Fortaleza - CE.

### ISSUE THREAD

**Issue by Tamiresbarretoo** [Rede-DSBR/CecateNE#252]
# 📝🖼️ Adaptar e produzir o Kit de Marca de implantação do Polo CECATE Ne em Recife - PE  e Fortaleza - CE.

## 📖 Descrição
O evento de formação do Cecate Nordeste ocorrerá em Recife, Pernambuco, nos dias 23 e 24 de julho de 2024 e em Fortaleza, Ceará, nos dias 25 e 26 de Julho. Destinado a Responsáveis ​​​​e Conselheiros do CACS dos Municípios da Região Intermediária, o encontro promoverá formação intensiva, discussão estratégica e troca de práticas com o FNDE para melhorar a gestão e promoção de políticas de transporte escolar.

## 🎯 Público-Alvo
Usuários e Designers do Projeto

## 🗓️ Data de Publicação Prevista
30.06.2024

## 📌 Observações Adicionais
A marca do kit será atualizada com as diretrizes específicas para o polo de Recife, Aracaju e Fortaleza.

## ✅ Revisores
@dudabastos1973 
@jalinegm 

## 🙋 Pessoa Responsável
@joy-araujo 
@Tamiresbarretoo 

## 🚀 Data de Início
25.06.2024

## 🏁 Data de Conclusão Prevista
30.06.2024

**Comment by joy-araujo** [comment]
**Marcas CECATE Ne Ceará Polo Fortaleza:**


![Marca CECATE Ne Ceará Polo Fortaleza vertical fundo branco  (2)](https://github.com/Rede-DSBR/CecateNE/assets/150853958/cd315d9c-7f6d-4556-aa09-2f63e08e004e)
![Marca CECATE Ne Ceará Polo Fortaleza vertical fundo cinza (2)](https://github.com/Rede-DSBR/CecateNE/assets/150853958/4e230be7-2ea4-4b84-91bf-2ddc0e021f2b)
![Marca CECATE Ne Ceará Polo Fortaleza horizontal Oficial (1)](https://github.com/Rede-DSBR/CecateNE/assets/150853958/04eb7c40-2ce0-44b2-b621-9f90a8efa945)
![Marca CECATE Ne Ceará Polo Fortaleza horizontal 2 Oficial](https://github.com/Rede-DSBR/CecateNE/assets/150853958/ffba355d-e575-4d81-aafe-97cbb8e2c5f2)
![Marca CECATE Ne Ceará Polo Fortaleza horizontal 2 Oficial](https://github.com/Rede-DSBR/CecateNE/assets/150853958/4a0913c5-adbd-4c73-b20b-21e59676b402)
![Marca CECATE Ne Ceará horizontal 2 (1)](https://github.com/Rede-DSBR/CecateNE/assets/150853958/47d50f7b-121c-46d6-a275-f7db16b0bb0b)

@jalinegm 
@dudabastos1973 
@Tamiresbarretoo

**Comment by joy-araujo** [comment]
**Marcas CECATE Ne Pernambuco Polo Recife:**

![Marca CECATE Ne Recife Polo Pernambuco horizontal Oficial](https://github.com/user-attachments/assets/4d3d9241-0396-4c3b-ac3b-89750139b47a)
![Marca CECATE Ne Recife Polo Pernambuco horizontal 2 Oficial](https://github.com/user-attachments/assets/6c46b26b-41d5-41d8-a5ac-35256702410d)
![Marca CECATE Ne Recife horizontal ](https://github.com/user-attachments/assets/5d7d8143-66a8-4d24-a49e-7c4073487041)
![Marca CECATE Ne Recife Polo Pernambuco vertical fundo branco](https://github.com/user-attachments/assets/d161b684-f9f2-4ae6-b9d7-09d5a5151338)
![Marca CECATE Ne Recife vertical](https://github.com/user-attachments/assets/cff58598-e818-4b4c-9ba9-da998c05fbb4)
![Marca CECATE Ne Recife  Polo Pernambuco vertical fundo cinza](https://github.com/user-attachments/assets/46603a52-659e-4cc4-9df7-b865afd10a39)
