### ISSUE TITLE
[🚌 Evento 2024-07-20] Formação e implantação do Polo Recife [2601]

### ISSUE THREAD

**Issue by jalinegm** [Rede-DSBR/CecateNE#261]
## 📋 Descrição do Evento

O evento de formação do Cecate Nordeste ocorrerá em Recife, Pernambuco, no dia 20 de julho de 2024, marcando o lançamento do primeiro Polo Territorial de Transporte Escolar em Pernambuco e que impactará 71 municípios. Destinado a responsáveis e conselheiros do CACS dos Municípios da Região Intermediária, o encontro promoverá formação intensiva, discussões estratégicas e troca de práticas com o FNDE para aprimorar a gestão e reforçar políticas do transporte escolar.

### Alinhamentos
- [x] #292
- [x] #295
- [x] Conversar com Detran e encaminhar e-mail de entendimentos
- [x] Conversar com Tribunal de Contas do Estado e encaminhar e-mail de entendimentos
- [x] Conversar com o Ministério Público Estadual e encaminhar e-mail de entendimentos
- [x] Conversar com o presidente da Amupe e encaminhar e-mail de entendimentos
- [x] Conversar com o presidente da Uncme e encaminhar e-mail de entendimentos
- [x] Conversar com o presidente da Undime e encaminhar e-mail de entendimentos

### Programação e Divulgação
- [x] Programação preliminar do evento
- [x] Publicar anúncio do evento
- [x] #262
- [x] #253
- [x] #288
- [x] #294

### Logística
- [x] Solicitar Passagens
- [x] Solicitar Diárias
- [x] Reservar Hotel
- [x] Solicitar informações de transporte e hospedagem dos participantes do FNDE e Equipe Cecate NE

### Local do Evento
- [x] Reservar local do evento
- [x] Atualizar lista com sugestões para almoço no google maps
- [x] #293
- [x] Solicitar apoio e recursos tecnológicos
- [x] Conversar com o responsável pelo apoio audiovisual e gravar o contato do Whatsapp
- [x] Consultar sobre disponibilidade e acesso aos banheiros - 1 com 2M e 1 com 2F
- [x] Consultar sobre disponibilidade, capacidade e acesso ao auditório principal - 250 pessoas
- [x] Consultar sobre disponibilidade de 02 microfones sem fio no auditório principal - Disponível
- [x] Consultar sobre disponibilidade de 02 microfones sem fio no auditório complementar - Disponível
- [x] Consultar sobre disponibilidade, capacidade e acesso ao auditório complementar - 50 pessoas
- [x] Água para a mesa - Disponível
- [x] Realizar testes de apresentação dos Slides e do vídeo no Auditório Principal
- [x] Realizar testes de apresentação dos Slides e do vídeo no Auditório Complementar
- [x] #284
- [x]  Definir local para mesa de credenciamento - Definido
- [x]  Verificar número de assentos e disponibilidade de mesa e 03 cadeiras para credenciamento - Disponível
- [x]  Verificar número de assentos e disponibilidade de 05 cadeiras na mesa solene - Disponível até 10
- [x]  Definir local para serviço de alimentação - Definido
- [x]  Informar ao fornecedor sobre o local para serviço de alimentação
- [x] Consultar sobre disponibilidade de Púlpito no auditório principal - Disponível
- [x] Consultar sobre tomadas para carregar o celular - Verificando disponibilidade
- [x] Procurar informações sobre estacionamento / orientação aos participantes - 20 vagas externas e 20 vagas internas
- [x] Verificar acesso Wifi e informação para a conexão dos participantes - Disponível, será disponibilizado QR Code
- [x] Providenciar cobertura audiovisual - Disponível equipe de assessoria, fotógrafo e jornalista
- [x] Entrar em contato com a mãe atípica para entender as necessidades específicas

### Secretaria
- [x]  Solicitar cobertura de ASCOM - Disponível equipe de assessoria, fotógrafo e jornalista
- [x]  Solicitar Cerimonialista - Não disponível
- [x]  Elaborar Roteiro do Cerimonial
- [x]  Encaminhar convite para a equipe FNDE
- [x]  Enviar convites para a Secretaria de Educação
- [x] #282
- [x] Organizar as pastas
- [x] #283

### Desenvolvimento
- [x] #264
- [x] #263
- [x] #289
- [x] Realizar atualização de dados no Painel de Formação
- [x] #281
- [x] #280

### Contratos
- [x]  Estruturar equipe local de apoio
- [x] Contratar Serviço de Alimentação - Em contratação
- [x]  Contratar Mestre de Cerimônias - Em contratação

### Materiais de Apoio

- [x] Comprar caixa com 200 canetas da cor azul
- [x] Comprar resma de papel A4
- [x] Display para fotos
- [x] Aquisição de Banners
- [x]  Organizar mesa de credenciamento

## 🤳🏼 Fotos e Vídeos do Evento

📸 Fotos e Vídeos do Encontro de Formação Conselheiros do CACS Fundeb e Gestores do Transporte Escolar em Recife, PE, 20 de agosto de 2024 disponíveis no link https://photos.app.goo.gl/P9qQiRnEud7Syg9c6

**Comment by RedeDSBR** [comment]
O evento transcorreu com sucesso, todas as tarefas foram cumpridas e a participação foi efetiva. Com nota de organização geral do evento de 4,7, numa escala de 0 a 5.
# Pontos de Melhoria
Numa análise preliminar, são pontos de melhoria o local do evento, o desenvolvimento dos temas, o tempo de fala na cerimônia de abertura, conforme descrito abaixo:
## Local do Evento
1. Pontualidade: É preciso mitigar o risco de atraso com o café da manhã e retorno do almoço.
2. Localização do evento: É necessário observar na escolha do local de evento o trânsito para chegada e saída dos participantes, a proximidade com lugares para almoçar, a disponibilidade de locais para estacionar.
3. Instalações: Sempre que possível, evitar o acesso por escadas, planejar o evento como se estivesse chovendo na cidade.

## Desenvolvimento dos Temas
1. Evitar tratar de assuntos sobre a realidade local sem o devido conhecimento e pesquisa anterior com diferentes atores e com diferentes pontos de vista.
2. É necessário evitar o prolongamento dos debates sobre o transporte escolar pela perspectiva do controle exercido dos órgãos e Conselhos, deixando uma atmosfera de problemas jurídicos futuros ou questionamentos. 
3. Evitar começar frases com **"Tem que...."**, principalmente, quando o tema tem apetite para polêmica e para ações de controle exercidos pelos órgãos.
4. Prever o(s) itinerário(s) das apresentações na exposição com diálogos sobre as atividades específicas e criar uma lista de perguntas mais frequentes, pontos polêmicos e quadro de informações para quem não tem tempo a partir da nuvem de palavras.
