### ISSUE TITLE
Adaptar kit da marca para o canal do Cecate no Youtube

### ISSUE THREAD

**Issue by jalinegm** [Rede-DSBR/CecateNE#270]
# 📝🖼️ Tarefa de Criação de Conteúdo: adaptação da marca para o canal no Youtube.

## 📖 Descrição
O canal do Youtube permite personalização do banner.  Dessa maneira, é importante a adaptação do conteúdo da marca para o novo canal: https://www.youtube.com/@cecatenordeste

## 📌 Tipo de Conteúdo
Imagem para banner do canal

Especificações:
A imagem precisa ter até 6Mb e pelo menos 2.048 x 1.152 pixels.

![image](https://github.com/Rede-DSBR/CecateNE/assets/37112456/51f395ae-af24-40a9-9061-5c5d33090733)

**Comment by jalinegm** [comment]
@dudabastos1973 também precisamos de arte para miniatura dos vídeos de transmissão.
Já criei os links no canal e temporariamente, deixei a dos slides. 
https://www.youtube.com/@cecatenordeste/streams

O tamanho da imagem é 16:9. Para o OBS também, caso queiramos que apareça algo durante a transmissão.
No caso, algum rodapé..

**Comment by dudabastos1973** [comment]
![image](https://github.com/Rede-DSBR/CecateNE/assets/144291118/8ab88e10-310c-44fa-aef2-82e184e2a578)

**Comment by dudabastos1973** [comment]
![Uploading 2560x1440 YouTube Tela.png…]()

**Comment by jalinegm** [comment]
![2560x1440 YouTube Tela](https://github.com/Rede-DSBR/CecateNE/assets/37112456/56d95fce-aceb-4dd5-8ac2-c66bff1f831b)

Configurado com sucesso! 🎉
