### ISSUE TITLE
[🖼️ Conteúdo]  Elaboração de conteúdo para redes sociais de inscrições abertas do Cecate Nordeste em Paraíba, Polo Campina Grande. 

### ISSUE THREAD

**Issue by Tamiresbarretoo** [Rede-DSBR/CecateNE#274]
# 📝🖼️  Elaboração de conteúdo para redes sociais de inscrições abertas do Cecate Nordeste em Paraíba, Polo Campina Grande. 

## 📖 Descrição
Criar um card informativo para divulgação das inscrições abertas, incluindo um link direto.

## 📌 Tipo de Conteúdo
Card Informativo:
Design de um card visualmente atrativo para redes sociais.
Incluir o texto: "Inscrições Abertas!" junto com o logo da organização.

## 🗓️ Data de Publicação Prevista
15/06/2024

## ✅ Revisores
@dudabastos1973 

## 🙋 Pessoa Responsável
@Tamiresbarretoo 
@joy-araujo 

## 🚀 Data de Início
13/06/2024

## 🏁 Data de Conclusão Prevista
15/06/2024

**Comment by joy-araujo** [comment]
**Card de Inscrições abertas:** Aprovado
![Prancheta 1](https://github.com/user-attachments/assets/ecb0a529-41d3-47b8-876c-a9bb6f61e573)
