### ISSUE TITLE
Desenvolvimento de solução para Comunicação em WhatsApp e SMS baseada em arquitetura de dados

### ISSUE THREAD

**Issue by potyrlucena** [Rede-DSBR/CecateNE#30]
### Atividades Vinculadas
- [x] https://github.com/Rede-DSBR/CecateNE/issues/131
- [x] https://github.com/Rede-DSBR/CecateNE/issues/132
- [x] https://github.com/Rede-DSBR/CecateNE/issues/133
- [ ] https://github.com/Rede-DSBR/CecateNE/issues/134
- [ ] https://github.com/Rede-DSBR/CecateNE/issues/135
- [x] https://github.com/Rede-DSBR/CecateNE/issues/136
- [x] https://github.com/Rede-DSBR/CecateNE/issues/137

**Comment by jalinegm** [comment]
### Atividades Vinculadas
- [ ] https://github.com/Rede-DSBR/CecateNE/issues/131
- [ ] https://github.com/Rede-DSBR/CecateNE/issues/132
- [ ] https://github.com/Rede-DSBR/CecateNE/issues/133
- [ ] https://github.com/Rede-DSBR/CecateNE/issues/134
- [ ] https://github.com/Rede-DSBR/CecateNE/issues/135
- [ ] https://github.com/Rede-DSBR/CecateNE/issues/136
- [ ] https://github.com/Rede-DSBR/CecateNE/issues/137

**Comment by jalinegm** [comment]
## Chatbot está rodando com número de teste da Meta

1) Criação do fluxo de diálogo no Dialogflow: https://dialogflow.cloud.google.com/#/agent/cecatene/

2) Criação de código para integrar o Dialogflow + Cloud API: https://github.com/jalinegm/cecatene-inscricao-dialogflow-node

3) Persistência dos dados pela API Google Sheets: https://docs.google.com/spreadsheets/d/1ruVdA2F1-ttMEme2BY-jzlaLXPibX1vRG85zyCthoik/edit#gid=0

4) Criação de função no Apps Script para converter um template do Google Docs em pdf: 
```
const SHEETID = '1ruVdA2F1-ttMEme2BY-jzlaLXPibX1vRG85zyCthoik';
const DOCID= '1BY-hFSbrdx-_CRG1t1-TYj3_IvRXJfrBetkcwQ3VAeE';
const FOLDERID= '1K0u72jjeOCJJK0LBg29qAvZcCM41CiKq'

function onOpen() {
  var ui = SpreadsheetApp.getUi();
  ui.createMenu('Certificados')
      .addItem('Gerar Certificado', 'gerarCertificado')
      .addToUi();
}



function gerarCertificado() {
  var sheet = SpreadsheetApp.openById(SHEETID).getSheetByName('data');
  var data = sheet.getDataRange().getValues();

  const temp = DriveApp.getFileById(DOCID);
  const folder = DriveApp.getFolderById(FOLDERID);

  var rows = data.slice(1);

  rows.forEach((row,index)=>{
     if (row[9] === ""){
    const file = temp.makeCopy(folder);
    const doc = DocumentApp.openById(file.getId());
    const body = doc.getBody();

    //altera os valores conforme o cabeçalho da planilha
    data[0].forEach((heading, i)=>{
      const header1 = heading.toUpperCase();
      body.replaceText(`{${header1}}`, row[i]);
    })

    doc.setName(row[3]+'_'+row[2]);
    const blob = doc.getAs(MimeType.PDF);
    doc.saveAndClose();

    const pdf = folder.createFile(blob).setName(row[3]+'_'+row[2]+'.pdf');

    const url = sheet.getRange(index+2,10,1,1);
    url.setValue(pdf.getUrl());
    file.setTrashed(true);
     }
  })
}
```
5) Deploy na Cloud Run **(necessário mudar token do whatsapp a cada 23h - número temporário)**
https://console.cloud.google.com/run/detail/us-central1/cecatene-inscricao-dialogflow-node/metrics?hl=en&project=cecatene

6) Configuração do Webhook:
https://cecatene-inscricao-dialogflow-node-i5zhebukzq-uc.a.run.app/webhook

**Comment by jalinegm** [comment]
Prof. Poty contratou Neuron para administrar os atendimentos por whatsapp.
