### ISSUE TITLE
Desenvolver identidade visual para o 📡 Embarque Digital

### ISSUE THREAD

**Issue by dudabastos1973** [Rede-DSBR/CecateNE#319]
**1. Proposta de Marca**
A identidade Visual do Embarque Digital norteará os visuais e ações necessárias de comunicação e design para no projeto do CECATE Nordeste. Aqui já apresentamos a proposta para apreciação e considerações. Estejam à vontade para tecer comentários.
![image](https://github.com/user-attachments/assets/949c9c04-fef5-4021-b15f-d98477fc46cf)

**2. Brandbook da Marca Embarque Digital.** 
Pequeno manual com algumas características de editoração e aplicação da marca em nossos materiais e mídias sociais.
Seções do Brand:
a. **Apresentação da Marca**: Breve história e essência da marca. Propósito da marca.
b. **Apresentação da Logo** em suas posturas e aplicações, versões monocromáticas e escala de cinzas
c. **Paleta de cores**: primárias e secundárias
d. **Tipografia**: fontes primárias e de apoio. 
e. **Elementos Gráficos**: Ícones, padrões, ilustrações e outros elementos visuais
f. **Exemplos de aplicação**: posturas em posts e anúncios, aplicações em mockups tipo camisa e caneca
g. **Diretrizes Fotográficas**: relações da marca com imagens. Estilo de fotografia ideais (tonalidade, foco, temas)
Exemplos de fotos adequadas para a marca
h. **Variações, usos corretos e incorretos**

**Prazo de entrega: 07/11/2024**

**3. Estratégias de Comunicação para divulgação**
Modelos e criações estratégicas para atuação nas redes do Cecate com o tom de voz do Embarque Digital. Nesta estratégia, cultivamos uma comunicação próxima e humanizada, reforçando o elo entre as ações do Embarque Digital e toda a experiência de formação on-line.

**Comment by dudabastos1973** [comment]
![image](https://github.com/user-attachments/assets/5c3d3cb4-5376-4dbf-89f1-b6a0d7662645)
Segue a proposta de marca do Embarque para apreciação e aprovação. Fiquem à vontade para qualquer consideração.

**Comment by potyrlucena** [comment]
Acho que podemos fazer um teste de marca com **Formação e Assistência Técnica On-line**

**Comment by dudabastos1973** [comment]
![image](https://github.com/user-attachments/assets/527da5f8-919f-471d-8300-e6b069264287)
@potyrlucena

**Comment by dudabastos1973** [comment]
![image](https://github.com/user-attachments/assets/68700bef-a0a6-4ff5-85be-c0bfcb6e9025)
imagem da versão final da marca Embarque Digital

**Comment by potyrlucena** [comment]
Marca aprovada!
