### ISSUE TITLE
Modelo de Certificado para Embarque Digital

### ISSUE THREAD

**Issue by jalinegm** [Rede-DSBR/CecateNE#327]
# 📝🖼️ Tarefa de Criação de Conteúdo

## 📖 Descrição
Criação de peça/mídia visual para os certificados das oficinas do programa Embarque Digital. A mídia deverá destacar o nome da atividade, pois haverá várias oficinas diferentes, e incluir um espaço para o código de validação, que estará localizado na parte inferior do certificado.

## 📌 Tipo de Conteúdo
Certificado de participação em oficinas.

## 📚 Tópicos a Serem Abordados
- Design que destaque o nome da atividade/oficina
- Espaço para código de validação
- Estilo visual coerente com a identidade do Embarque Digital

## 🎯 Objetivo do Conteúdo
Criar um design de certificado que seja claro, visualmente atraente e adequado para destacar cada oficina individualmente, além de permitir a validação do certificado. A mídia será usada como plano de fundo em um slide, no Google Slides para posterior geração automática dos certificados com esse modelo.

## 🎯 Público-Alvo
Participantes das oficinas do Embarque Digital.

## 🗓️ Data de Publicação Prevista
13/11/2024, após a oficina do Sistema SETE

## 🖼️ Mídia
TAMANHO: Widescreen 16:9

![MODELO  Rec_EquipeOrganizadora_Certificado](https://github.com/user-attachments/assets/4996dfd2-13c9-4d95-98e1-951a8d6488ae)

## 📌 Observações Adicionais
O design deve permitir a personalização do nome da atividade/oficina, além do texto que é gerado automaticamente pela ferramenta que gera os certificados. É muito importante manter o espaço para o código de validação, com contraste para texto na cor branca ou escura.

## ✅ Revisores
- @potyrlucena 

## 🙋 Pessoa Responsável
@dudabastos1973 

## 🚀 Data de Início
11/11/2024

## 🏁 Data de Conclusão Prevista
12/11/2024

**Comment by dudabastos1973** [comment]
https://www.canva.com/design/DAGWM6ugQqM/yycVnOdevQP1c7qxSZbplg/edit

segue o modelo de certificado. A segunda proposta é a versão do diretor

**Comment by jalinegm** [comment]
Aprovado pelo Prof. Poty e já configurado no Google Slides.
