### ISSUE TITLE
Configuração do envio dos certificados

### ISSUE THREAD

**Issue by jalinegm** [Rede-DSBR/CecateNE#335]
Modelo criado pelo Duda e configurado no Autocrat.

**Comment by jalinegm** [comment]
Prof. @potyrlucena, por favor, valide o texto do certificado (criado por Duda) e do corpo do e-mail? Foi um enviado como teste para o e-mail do Cecate.

**Comment by potyrlucena** [comment]
## Texto corrigido

**Certificado**

Certificamos que <NOME> participou da   Oficina do Sistema SETE, realizada no dia 13 de novembro de 2024, transmitida pela plataforma de transmissão do Cecate Nordeste, via Google Meet., com uma carga horária total de 1 hora. O evento foi promovido pelo Cecate Nordeste, Centro Colaborador de Apoio ao Transporte Escolar da Região Nordeste do Fundo Nacional de Desenvolvimento da Educação (FNDE).

![image](https://github.com/user-attachments/assets/c1adf224-f739-4fa5-b335-f6563f0c4784)

**Comment by jalinegm** [comment]
111 certificados enviados preliminarmente.
Relatório adicionado no padrão que é solicitado pelo FNDE:
https://drive.google.com/drive/u/3/folders/1_47zklgOzKV6SUxA5qIHuB43TNwYAw2W
