### ISSUE TITLE
[🖼️ Cartilha de Perguntas e Respostas do Embarque Digital]

### ISSUE THREAD

**Issue by dudabastos1973** [Rede-DSBR/CecateNE#338]
# 📝🖼️  Cartilha de Perguntas e Respostas do Embarque Digital

📖 **Descrição**
A cartilha "Perguntas e Respostas do Embarque Digital" é um guia prático, desenvolvido para fornecer suporte claro e direto aos participantes do Programa Embarque Digital, do Cecate Nordeste. Este material ilustrado complementa a formação on-line, servindo como referência rápida para as principais dúvidas e procedimentos técnicos, além de promover uma interação mais acessível e eficiente com o conteúdo do programa.

📌 Tipo de Conteúdo
Cartilha ilustrada em formato PDF, com foco em perguntas e respostas.

📚 **Tópicos a Serem Abordados**
1. Introdução ao Programa Embarque Digital
2. Passo a passo de acesso e navegação na plataforma
3. Ferramentas e funcionalidades disponíveis
4. Suporte técnico e canais de ajuda
5. Melhores práticas para o uso do material de formação
**6. Perguntas frequentes sobre o programa e seus conteúdos**

🎯 **Objetivo do Conteúdo**
O objetivo principal é orientar e facilitar a navegação dos participantes pela plataforma do Embarque Digital, promovendo autonomia no acesso e aproveitamento do conteúdo. A cartilha visa também sanar dúvidas frequentes, tornando o aprendizado mais acessível e fluido.

🎯 **Público-Alvo**
Participantes do Programa Embarque Digital, incluindo educadores, gestores e técnicos que utilizam o conteúdo para formação e assistência técnica. Participantes dos Eventos de Formação On-line.

🗓️ **Data de Publicação Prevista**
Um volume para cada Oficina realizada. Os volumes serão apensados para formar uma cartilha geral.

🛠️ **Recursos Necessários**
1. Design gráfico para ilustrações e diagramação
2. Equipe de suporte para coleta de perguntas frequentes e dúvidas recorrentes
3. Plataforma para hospedagem e acesso ao material em formato PDF
4. Revisão editorial para clareza e adequação da linguagem
5. Divulgação pelo Whatsapp

🖼️ **Mídia**
Imagens e ilustrações de apoio sobre as funcionalidades da plataforma, além de capturas de tela da interface do Embarque Digital, para facilitar a orientação visual. Texto coletado das sessões de formação.

📌 **Observações Adicionais**
O material deve ser acessível e otimizado para leitura em dispositivos móveis.

## ✅ **Revisores**
@Kelliconsuelo 
@Catia1409 
@Marcoswilians 
@potyrlucena 
@jalinegm 

## 🙋 **Pessoa Responsável**
@dudabastos1973 

## 🚀 **Data de Início**
14.11.24

## 🏁 **Data de Conclusão Prevista**
a definir

**Comment by jalinegm** [comment]
Oi, pessoal! Segue os links importantes da oficina:

📄Documento com as questões que fomos copiando e colando durante a oficina:
https://docs.google.com/document/d/1QSdI0uJWgxwb6Coq1_foH9yDeEMpTne5bDT8Yp111U4/edit?tab=t.0

Aúdio, transcrição e o arquivo com o chat (registro do Lean) estão na pasta do Drive ⬇️

**📁 Pasta do Drive do CecateNe (mesmo diretório que a Profa. Kelli criou):**
https://drive.google.com/open?id=1OTHD-xXYgtQZvgut5W6TlzKiEQK2UX1Q&usp=drive_fs

**Comment by dudabastos1973** [comment]
[Perguntas & Respostas Oficina SETE - Caderno I Embarque Digital.pdf](https://github.com/user-attachments/files/17908294/Perguntas.Respostas.Oficina.SETE.-.Caderno.I.Embarque.Digital.pdf)
