### ISSUE TITLE
[🖼️ Conteúdo] Adaptação dos slides da 2ª atividade do Embarque Digital

### ISSUE THREAD

**Issue by jalinegm** [Rede-DSBR/CecateNE#341]
# 📝🖼️ Tarefa de Criação de Conteúdo

## 📖 Descrição
Adaptar os slides da oficina de prestação de contas para a identidade visual do programa **Embarque Digital**. A adaptação deverá alinhar os elementos visuais dos slides existentes ao padrão estabelecido no modelo de referência.

## 📌 Tipo de Conteúdo
Apresentação de slides

## 📚 Tópicos a Serem Abordados
- Manutenção do conteúdo original da oficina de prestação de contas
- Aplicação do design visual consistente com o **Embarque Digital**

## 🎯 Objetivo do Conteúdo
Atualizar o visual da apresentação para reforçar a identidade institucional do  **Embarque Digital**, garantindo uma comunicação visual mais coerente e alinhada com a marca.

## 🎯 Público-Alvo
Participantes da oficina de prestação de contas e gestores envolvidos no **Embarque Digital**.

## 🗓️ Data de Publicação Prevista
26/11/2024

## 🛠️ Recursos Necessários
- Arquivos originais dos slides:
  - [Slide 1 para editar](https://www.canva.com/design/DAGVhdVz5-Y/Toy51YW_c7c-WVVOf1dr1Q/edit)
  - [Slide 2 para editar](https://www.canva.com/design/DAGVhpFG9IM/NS0Xz0L8a6RTX5VLNxhz7g/edit)
- Modelo de identidade visual do **Embarque Digital**:
  - [Modelo de referência](https://www.canva.com/design/DAGWON0EjY8/5Ch4VkU8HwUlYUtja4Stlg/edit)

## ✅ Revisores
- @Marcoswilians 
- @dudabastos1973 

## 🙋 Pessoa Responsável
@lucrafi22 
@Lean-77   

## 🚀 Data de Início
18/11/2024

## 🏁 Data de Conclusão Prevista
25/11/2024

**Comment by lucrafi22** [comment]
Adaptação dos slides da 2ª atividade do Embarque Digital concluída. Aguardo a avaliação e revisão: @dudabastos1973 e revisão do conteúdo por @Marcoswilians.
@lucrafi22 e @Lean-77

**Comment by jalinegm** [comment]
Atividade finalizada:
https://www.canva.com/design/DAGVhdVz5-Y/Rlxiqt2mkku9ejW2yiWZEA/view?utm_content=DAGVhdVz5-Y&utm_campaign=designshare&utm_medium=link&utm_source=editor
