### ISSUE TITLE
[📝🖼️ Conteúdo] Elaboração e organização do material referente à atividade II do Embarque Digital

### ISSUE THREAD

**Issue by Lean-77** [Rede-DSBR/CecateNE#344]
# 📝🖼️ Tarefa de Criação de Conteúdo

## 📖 Descrição
Organização lógica do material **didático-pedagógico** para a oficina II do Embarque Digital, referente as **Prestações de contas: PNATE e Caminho da Escola**, além das adaptações sujeitas a mudanças dos painéis em função da nova identidade visual do programa Embarque Digital a serem utilizados durante a formação online. 

## 📌 Tipo de Conteúdo
Apresentação dos Painéis digitais.

## 📚 Tópicos a Serem Abordados
- Prestação de Conta conforme a Resolução MEC/FNDE/CD nº 18, de 22 de outubro de 202: 
1. SIGPC
2. BB Gestão Ágil
- Prestação de conta:
1. SIMEC
 - Resolução Nº2, de 07/06/2024 que Dispõe sobre o 4º Ciclo do Plano de Ações Articuladas - PAR (2021-2024);
 - Resolução FNDE Nº22, de 22/09/2024;
- Altera a Resolução CD/FNDE nº 7, de 2 de maio de 2024;
- Implementação do design visual da nova identidade do Embarque Digital (sujeito a alterações).

## 🎯 Objetivo do Conteúdo

- Revisar e elaborar material didático-pedagógico para a oficina II do Embarque Digital;
- Atualizar o visual de apresentação com viés da identidade institucional do Embarque Digital, fortalecendo a comunicação alinhada com a marca. 

## 🎯 Público-Alvo

- Participantes da oficina de Prestações de contas: PNATE e Caminho da Escola e gestores envolvidos no Embarque Digital.

## 🗓️ Data de Publicação Prevista
26/11/2024

## 🛠️ Recursos Necessários
<https://acesse.one/Canvamaterial>

## 📌 Observações Adicionais

- A funções visuais de cada apresentação podem estarem sujeitas a novas alterações conforme as demandas da próxima reunião com a equipe.

## ✅ Revisores
- @Marcoswilians 
- @Kelliconsuelo 
- @dudabastos1973 

## 🙋 Pessoa Responsável

- @Lean-77 
- @lucrafi22 
- @jalinegm 

## 🚀 Data de Início
18/11/2024

## 🏁 Data de Conclusão Prevista
25/11/2024

## 😎 Registro da reunião (21/11/2024): Revisão/Elaboração do material didático-pedagógico para a atividade II do Embarque Digital e estruturação visual da nova identidade
![Imagem do WhatsApp de 2024-11-21 à(s) 19 27 49_b8a53e59](https://github.com/user-attachments/assets/3ac90d8a-bb31-4eb5-a166-47439f8cef64)

**Comment by jalinegm** [comment]
Conteúdo editado e disponível em:
https://www.canva.com/design/DAGVhdVz5-Y/Rlxiqt2mkku9ejW2yiWZEA/view?utm_content=DAGVhdVz5-Y&utm_campaign=designshare&utm_medium=link&utm_source=editor
