### ISSUE TITLE
Desenvolvimento de "canal direto" de Assistência Técnica para monitoramento contínuo

### ISSUE THREAD

**Issue by potyrlucena** [Rede-DSBR/CecateNE#68]
@RedeDSBR 

Primeira versão criada na pasta de [Formação/Assistência Técnica](https://drive.google.com/drive/folders/1C4ZfUR0uyJlc872gA0mgUz804swScgre?usp=drive_link)

https://forms.gle/C8SypsXMaQaDWfof9

Entretanto, não consegui colocar upload de arquivo pela conta do CecateNe. A UFOB precisa permitir ou precisamos criar uma cópia com a conta da DSBR e compartilhar com o e-mail do CecateNe para edição.

**Comment by jalinegm** [comment]
Prof. Poty contratou Neuron para administrar os atendimentos por whatsapp.
